interface LineChartProps { series?: number[]; values?: number[]; forecast?: number[]; upper?: number[]; threshold?: number; labels?: string[] }

function points(values: number[], width: number, height: number, offset: number, max: number) { return values.map((value, index) => `${offset + index * (width / Math.max(1, values.length - 1))},${height - 18 - (value / max) * (height - 34)}`).join(' '); }

export function LineChart({ series: seriesProp = [], values, forecast = [], upper = [], threshold }: LineChartProps) {
  const series = values ?? seriesProp;
  const all = [...series, ...forecast, ...upper, threshold ?? 0];
  const max = Math.max(100, ...all);
  const width = 720; const height = 240; const split = series.length ? width * series.length / Math.max(1, series.length + forecast.length) : width;
  return <div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Utilization trend chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#4a8dff" stopOpacity=".25"/><stop offset="1" stopColor="#4a8dff" stopOpacity="0"/></linearGradient></defs>{[20,40,60,80,100].map((tick) => <line key={tick} x1="0" x2={width} y1={height - 18 - (tick / max) * (height - 34)} y2={height - 18 - (tick / max) * (height - 34)} className="chart-grid" />)}{threshold !== undefined && <line x1="0" x2={width} y1={height - 18 - (threshold / max) * (height - 34)} y2={height - 18 - (threshold / max) * (height - 34)} className="threshold-line" />}{series.length > 1 && <><polygon points={`0,${height - 18} ${points(series, split, height, 0, max)} ${split},${height - 18}`} fill="url(#area)"/><polyline points={points(series, split, height, 0, max)} className="chart-line actual" /></>}{forecast.length > 1 && <polyline points={points(forecast, width - split, height, split, max)} className="chart-line forecast" />}{upper.length > 1 && <polyline points={points(upper, width - split, height, split, max)} className="chart-line upper" />}</svg><div className="chart-legend"><span><i className="legend-dot actual-dot"/>Historical</span><span><i className="legend-dot forecast-dot"/>Simulation Forecast</span>{threshold !== undefined && <span><i className="legend-dot threshold-dot"/>Threshold</span>}</div></div>;
}
