import { publicClient } from '@dynatrace-sdk/client-davis-copilot';
import { queryExecutionClient } from '@dynatrace-sdk/client-query';
import type { ForecastHorizon, Host } from '@/types';
import { getDynatraceForecasts, type DynatraceForecast } from './dynatraceIntelligence';
import { runCapacitySimulation } from './services/capacitySimulation';

type RecordRow = Record<string, unknown>;
interface QueryResult { records?: Array<RecordRow | null> }
export interface CapacityAiContext { managementZone:string; timeRange:string; forecastHorizon:ForecastHorizon; hosts:Host[]; forecasts:Array<{host:Host;forecast:DynatraceForecast}>; simulation?:{trafficGrowth:number;projectedCpu?:number;projectedMemory?:number;projectedDisk?:number;additionalHosts?:number;capacityGap?:number;risk?:string;currentTraffic?:number;projectedTraffic90d?:number}; }
const MAX_PROMPT=8500; const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms)); const escDql=(v:string)=>v.replace(/\\/g,'\\\\').replace(/"/g,'\\"'); const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0;};
async function dql(query:string,max=300):Promise<RecordRow[]>{const response=await queryExecutionClient.queryExecute({body:{query,requestTimeoutMilliseconds:30000,maxResultRecords:max}});let result=response.result as QueryResult|undefined,token=response.requestToken,state=response.state;for(let i=0;!result&&token&&i<30;i++){const p=await queryExecutionClient.queryPoll({requestToken:token,requestTimeoutMilliseconds:30000});result=p.result as QueryResult|undefined;state=p.state;if(!result&&state==='RUNNING')await sleep(250);}if(!result)throw new Error(`DQL tool did not complete (state: ${state}).`);return(result.records??[]).filter(Boolean) as RecordRow[];}
function avg(hosts:Host[],key:'cpu'|'memory'|'disk'){return hosts.length?hosts.reduce((s,h)=>s+(h.telemetry.at(-1)?.[key]??0),0)/hosts.length:0;} function traffic(hosts:Host[]){return hosts.reduce((s,h)=>s+(h.telemetry.at(-1)?.throughput??0),0);} function compactHosts(hosts:Host[]){return hosts.map(h=>{const p=h.telemetry.at(-1);return{name:h.name,id:h.id,application:h.application,environment:h.environment,profile:h.profile,cpu:+(p?.cpu??0).toFixed(1),memory:+(p?.memory??0).toFixed(1),disk:+(p?.disk??0).toFixed(1),throughput:+(p?.throughput??0).toFixed(1)};});} function growthFrom(q:string){const m=q.match(/(\d+(?:\.\d+)?)\s*%/);if(!m||!/(traffic|request|load|throughput)/i.test(q))return null;const x=Number(m[1]);return Number.isFinite(x)&&x>=0&&x<=500?x:null;} function daysFrom(q:string){const m=q.match(/last\s+(\d+)\s+days?/i);const x=m?Number(m[1]):30;return Number.isFinite(x)?Math.min(Math.max(x,1),90):30;} function hostFilter(hosts:Host[]){return hosts.slice(0,300).map(h=>`"${escDql(h.id)}"`).join(', ');}
function simulation(hosts:Host[],growth:number){const currentTraffic=Math.max(1,traffic(hosts));const result=runCapacitySimulation({cpuCapacity:Math.max(1,avg(hosts,'cpu')),memoryCapacity:Math.max(1,avg(hosts,'memory')),diskCapacity:Math.max(1,avg(hosts,'disk')),trafficGrowth:growth,transactionGrowth:growth,period:90 as ForecastHorizon,additionalHosts:0,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});return{trafficGrowth:growth,currentTraffic,projectedTraffic90d:currentTraffic*(1+growth/100),projectedCpu:result.projectedCpu,projectedMemory:result.projectedMemory,projectedDisk:result.projectedDisk,additionalHosts:result.requiredHosts,capacityGap:result.capacityGap,risk:result.risk};}
function riskSnapshot(hosts:Host[]){return[...hosts].map(h=>{const p=h.telemetry.at(-1);const max=Math.max(p?.cpu??0,p?.memory??0,p?.disk??0);return{host:h.name,application:h.application,cpu:+(p?.cpu??0).toFixed(1),memory:+(p?.memory??0).toFixed(1),disk:+(p?.disk??0).toFixed(1),max:+max.toFixed(1)};}).sort((a,b)=>b.max-a.max).slice(0,10);}
async function problemTool(hosts:Host[],days:number){const ids=hostFilter(hosts);if(!ids)return{windowDays:days,total:0,active:0,topProblems:[] as Array<{title:string;count:number}>};const base=`fetch dt.davis.problems, from:now()-${days}d, to:now() | filter not(dt.davis.is_duplicate) | expand affected_entity_ids | filter in(affected_entity_ids, ${ids})`;const [countRows,activeRows,topRows]=await Promise.all([dql(`${base} | summarize total=countDistinct(event.id)`,5),dql(`${base} | filter event.status == "ACTIVE" | summarize active=countDistinct(event.id)`,5),dql(`${base} | summarize count=countDistinct(event.id), by:{event.name} | sort count, direction:"descending" | limit 5`,10)]);return{windowDays:days,total:Math.round(n(countRows[0]?.total)),active:Math.round(n(activeRows[0]?.active)),topProblems:topRows.map(r=>({title:String(r['event.name']??'Unnamed problem'),count:Math.round(n(r.count))}))};}
async function memoryTrendTool(hosts:Host[]){const ids=hostFilter(hosts);if(!ids)return[];const rows=await dql(`timeseries memory=avg(dt.host.memory.usage), by:{dt.entity.host}, interval:6h, from:-7d, to:now() | filter in(dt.entity.host, ${ids}) | fields dt.entity.host, memory, timeframe, interval`,100);return rows.slice(0,25).map(r=>({host:String(r['dt.entity.host']??''),memory:r.memory,timeframe:r.timeframe,interval:r.interval}));}
async function forecastTool(hosts:Host[],horizon:ForecastHorizon){const forecasts=await getDynatraceForecasts(hosts,'cpu',horizon);return forecasts.slice(0,25).map(({host,forecast})=>({host:host.name,metric:forecast.metric,horizon:forecast.horizon,peak:forecast.forecast.length?Math.max(...forecast.forecast):null,upper:forecast.upperBound.length?Math.max(...forecast.upperBound):null,quality:forecast.quality,status:forecast.status}));}
async function arbitraryDqlTool(question:string,zone:string,hosts:Host[]){const ids=hostFilter(hosts);const response=await publicClient.nl2dql({body:{text:`Generate ONE read-only executable DQL query for this capacity-planning question: ${question}. Selected Management Zone: ${zone}. Selected host ids: [${ids}]. Restrict infrastructure results to these host ids when host filtering is applicable. Use only Dynatrace Grail data. Return only DQL, no markdown.`}});const generated=String((response as {dql?:string}).dql??'').trim();if(!generated)throw new Error('Davis NL-to-DQL returned no query.');return{dql:generated,rows:await dql(generated,100)};}
async function synthesize(question:string,context:CapacityAiContext,evidence:Record<string,unknown>){const prompt=`You are Davis, an interactive capacity-planning advisor for an Axis Bank SRE team. Answer the user's question using the live Dynatrace context and tool evidence below. Never invent values. Distinguish observed telemetry, DQL results, forecast results and simulations. If evidence is insufficient, state exactly what is missing. Give a direct answer first, then concise supporting details. User question: ${question}\n\nSelected Management Zone: ${context.managementZone}\nLive host snapshot: ${JSON.stringify(compactHosts(context.hosts))}\nTool evidence: ${JSON.stringify(evidence)}`;const text=prompt.length<=MAX_PROMPT?prompt:`${prompt.slice(0,MAX_PROMPT-180)}\n[Context truncated. Do not infer omitted data.]`;const response=await publicClient.recommenderConversation({body:{text,context:[{type:'instruction',value:'Use only the supplied live/tool evidence. Keep the answer under 350 words. Do not expose internal reasoning.'}]}});const answer=(response as {text?:string;answer?:string;content?:string}).text??(response as {answer?:string}).answer??(response as {content?:string}).content??'';if(!String(answer).trim())throw new Error('Davis returned an empty answer.');return String(answer).trim();}
export async function askAgenticDavisV51(question:string,context:CapacityAiContext){const q=question.trim();if(!q)throw new Error('Please enter a capacity-planning question.');const lower=q.toLowerCase();const evidence:Record<string,unknown>={};const growth=growthFrom(q);if(growth!==null)evidence.capacitySimulation=simulation(context.hosts,growth);if(/\b(problem|problems|incident|incidents|outage|outages)\b/i.test(q))evidence.davisProblems=await problemTool(context.hosts,daysFrom(q));else if(/closest|highest|top|risk|risky|cpu capacity|memory capacity|disk capacity/i.test(lower))evidence.capacityRiskSnapshot=riskSnapshot(context.hosts);else if(/primary capacity constraint|main capacity constraint|bottleneck|constrained resource/i.test(lower)){const a={cpu:avg(context.hosts,'cpu'),memory:avg(context.hosts,'memory'),disk:avg(context.hosts,'disk')};evidence.currentResourceAverages=a;evidence.primaryConstraint=Object.entries(a).sort((x,y)=>(y[1] as number)-(x[1] as number))[0];}else if(/memory trend|memory history|memory over|memory usage trend/i.test(lower))evidence.memoryTrend=await memoryTrendTool(context.hosts);else if(/forecast|predict|prediction|projected|future capacity|next \d+ days/i.test(lower))evidence.forecast=await forecastTool(context.hosts,context.forecastHorizon);else{try{evidence.grailQuery=await arbitraryDqlTool(q,context.managementZone,context.hosts);}catch(error){evidence.grailQueryError=error instanceof Error?error.message:String(error);}}return synthesize(q,context,evidence);}
export const suggestedCapacityQuestions=['Which hosts are closest to CPU capacity?','What are the top capacity risks in this Management Zone?','What happens if traffic increases by 48%?','Which resource is the primary capacity constraint?','How many infrastructure problems were generated in the last 30 days?','What is the current memory trend for this Management Zone?','Summarize the capacity outlook for the next 30 days?'];
