import { publicClient, type State } from '@dynatrace-sdk/client-davis-copilot';
import { queryExecutionClient } from '@dynatrace-sdk/client-query';
import type { ForecastHorizon, Host } from '@/types';
import { getDynatraceForecasts, type DynatraceForecast } from './dynatraceIntelligence';
import { runCapacitySimulation } from './services/capacitySimulation';

type RecordRow = Record<string, unknown>;
interface QueryResult { records?: Array<RecordRow | null> }
export interface CapacityAiContext { managementZone:string; timeRange:string; forecastHorizon:ForecastHorizon; hosts:Host[]; forecasts:Array<{host:Host;forecast:DynatraceForecast}>; simulation?:{trafficGrowth:number;projectedCpu?:number;projectedMemory?:number;projectedDisk?:number;additionalHosts?:number;capacityGap?:number;risk?:string;currentTraffic?:number;projectedTraffic90d?:number}; }
export interface CapacityAiResponse { answer:string; state?:State; mode:'tool-assisted'|'fallback'; }
const MAX_SUPPLEMENTARY=7000;
const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
const escDql=(v:string)=>v.replace(/\\/g,'\\\\').replace(/"/g,'\\"');
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0;};
async function dql(query:string,max=200):Promise<RecordRow[]>{const response=await queryExecutionClient.queryExecute({body:{query,requestTimeoutMilliseconds:30000,maxResultRecords:max}});let result=response.result as QueryResult|undefined,token=response.requestToken,state=response.state;for(let i=0;!result&&token&&i<30;i++){const p=await queryExecutionClient.queryPoll({requestToken:token,requestTimeoutMilliseconds:30000});result=p.result as QueryResult|undefined;state=p.state;if(!result&&state==='RUNNING')await sleep(250);}if(!result)throw new Error(`DQL tool did not complete (state: ${state}).`);return(result.records??[]).filter(Boolean) as RecordRow[];}
function avg(hosts:Host[],key:'cpu'|'memory'|'disk'){return hosts.length?hosts.reduce((s,h)=>s+(h.telemetry.at(-1)?.[key]??0),0)/hosts.length:0;}
function traffic(hosts:Host[]){return hosts.reduce((s,h)=>s+(h.telemetry.at(-1)?.throughput??0),0);}
function compactHosts(hosts:Host[]){return hosts.map(h=>{const p=h.telemetry.at(-1);return{name:h.name,id:h.id,application:h.application,environment:h.environment,profile:h.profile,cpu:+(p?.cpu??0).toFixed(1),memory:+(p?.memory??0).toFixed(1),disk:+(p?.disk??0).toFixed(1),throughput:+(p?.throughput??0).toFixed(1)};});}
function growthFrom(q:string){const m=q.match(/(\d+(?:\.\d+)?)\s*%/);if(!m||!/(traffic|request|load|throughput)/i.test(q))return null;const x=Number(m[1]);return Number.isFinite(x)&&x>=0&&x<=500?x:null;}
function daysFrom(q:string){const m=q.match(/last\s+(\d+)\s+days?/i);const x=m?Number(m[1]):30;return Number.isFinite(x)?Math.min(Math.max(x,1),90):30;}
function hostFilter(hosts:Host[]){return hosts.slice(0,300).map(h=>`\"${escDql(h.id)}\"`).join(', ');}
function simulation(hosts:Host[],growth:number){const currentTraffic=Math.max(1,traffic(hosts));const result=runCapacitySimulation({cpuCapacity:Math.max(1,avg(hosts,'cpu')),memoryCapacity:Math.max(1,avg(hosts,'memory')),diskCapacity:Math.max(1,avg(hosts,'disk')),trafficGrowth:growth,transactionGrowth:growth,period:90 as ForecastHorizon,additionalHosts:0,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});return{trafficGrowth:growth,currentTraffic,projectedTraffic90d:currentTraffic*(1+growth/100),projectedCpu:result.projectedCpu,projectedMemory:result.projectedMemory,projectedDisk:result.projectedDisk,additionalHosts:result.requiredHosts,capacityGap:result.capacityGap,risk:result.risk};}
function riskSnapshot(hosts:Host[]){return[...hosts].map(h=>{const p=h.telemetry.at(-1);const values={cpu:p?.cpu??0,memory:p?.memory??0,disk:p?.disk??0};const resource=Object.entries(values).sort((a,b)=>b[1]-a[1])[0];return{host:h.name,application:h.application,cpu:+values.cpu.toFixed(1),memory:+values.memory.toFixed(1),disk:+values.disk.toFixed(1),max:+resource[1].toFixed(1),resource:resource[0]};}).sort((a,b)=>b.max-a.max).slice(0,10);}
async function problemTool(hosts:Host[],days:number){const ids=hostFilter(hosts);if(!ids)return{windowDays:days,total:0,active:0,topProblems:[] as Array<{title:string;count:number}>};const base=`fetch dt.davis.problems, from:now()-${days}d, to:now() | filter not(dt.davis.is_duplicate) | expand affected_entity_ids | filter in(affected_entity_ids, ${ids})`;const [countRows,activeRows,topRows]=await Promise.all([dql(`${base} | summarize total=countDistinct(event.id)`,5),dql(`${base} | filter event.status == \"ACTIVE\" | summarize active=countDistinct(event.id)`,5),dql(`${base} | summarize count=countDistinct(event.id), by:{event.name} | sort count, direction:\"descending\" | limit 5`,10)]);return{windowDays:days,total:Math.round(n(countRows[0]?.total)),active:Math.round(n(activeRows[0]?.active)),topProblems:topRows.map(r=>({title:String(r['event.name']??'Unnamed problem'),count:Math.round(n(r.count))}))};}
async function memoryTrendTool(hosts:Host[]){const ids=hostFilter(hosts);if(!ids)return[];const rows=await dql(`timeseries memory=avg(dt.host.memory.usage), by:{dt.entity.host}, interval:6h, from:-7d, to:now() | filter in(dt.entity.host, ${ids}) | fields dt.entity.host, memory, timeframe, interval`,50);return rows.slice(0,15).map(r=>({host:String(r['dt.entity.host']??''),memory:r.memory,timeframe:r.timeframe,interval:r.interval}));}
async function forecastTool(hosts:Host[],horizon:ForecastHorizon){const forecasts=await getDynatraceForecasts(hosts,'cpu',horizon);return forecasts.slice(0,20).map(({host,forecast})=>({host:host.name,metric:forecast.metric,horizon:forecast.horizon,peak:forecast.forecast.length?Math.max(...forecast.forecast):null,upper:forecast.upperBound.length?Math.max(...forecast.upperBound):null,quality:forecast.quality,status:forecast.status}));}
async function arbitraryDqlTool(question:string,zone:string,hosts:Host[]){const ids=hostFilter(hosts);const response=await publicClient.nl2dql({body:{text:`Generate ONE read-only executable DQL query for this Axis Bank capacity-planning question. Selected Management Zone: ${zone}. Host IDs for scoping: [${ids}]. User question: ${question}. When the question concerns infrastructure capacity, resource utilization, throughput, hosts, or problems, restrict results to the supplied host IDs where applicable. Include the requested time range from the user question. Return a single executable DQL query only.`}});if(response.status==='FAILED')throw new Error('Davis NL-to-DQL failed.');const generated=String(response.dql??'').trim();if(!generated)throw new Error('Davis NL-to-DQL returned no DQL.');return{dql:generated,rows:await dql(generated,100)};}
function evidenceForQuestion(context:CapacityAiContext,evidence:Record<string,unknown>){if(evidence.capacitySimulation){const x=evidence.capacitySimulation as {trafficGrowth:number;projectedCpu:number;projectedMemory:number;projectedDisk:number;capacityGap:number;risk:string;additionalHosts:number;projectedTraffic90d:number};return`At +${x.trafficGrowth}% traffic growth, the 90-day simulation projects ${x.projectedTraffic90d.toFixed(1)} req/min, CPU ${x.projectedCpu.toFixed(1)}%, memory ${x.projectedMemory.toFixed(1)}%, disk ${x.projectedDisk.toFixed(1)}%, capacity gap ${x.capacityGap}, risk ${x.risk}, and ${x.additionalHosts} additional host(s).`;} if(evidence.davisProblems){const p=evidence.davisProblems as {windowDays:number;total:number;active:number;topProblems:Array<{title:string;count:number}>};return`In the last ${p.windowDays} days there were ${p.total} distinct Davis problems, ${p.active} currently active. Top problem groups: ${p.topProblems.map(x=>`${x.title} (${x.count})`).join('; ')||'none'}.`;} if(evidence.capacityRiskSnapshot){const rows=evidence.capacityRiskSnapshot as Array<{host:string;cpu:number;memory:number;disk:number;max:number;resource:string}>;return`Top capacity risks from live telemetry: ${rows.slice(0,5).map(r=>`${r.host}: ${r.resource} ${r.max}% (CPU ${r.cpu}%, Memory ${r.memory}%, Disk ${r.disk}%)`).join('; ')||'none identified'}.`;} if(evidence.primaryConstraint){const x=evidence.primaryConstraint as [string,number];return`The highest current average utilization is ${x[0]} at ${(x[1] as number).toFixed(1)}%. CPU is ${avg(context.hosts,'cpu').toFixed(1)}%, memory ${avg(context.hosts,'memory').toFixed(1)}%, and disk ${avg(context.hosts,'disk').toFixed(1)}%.`;} if(evidence.memoryTrend){const rows=evidence.memoryTrend as Array<{host:string}>;return`Live memory trend data was retrieved for ${rows.length} host record(s) over the last 7 days. Current average memory is ${avg(context.hosts,'memory').toFixed(1)}%.`+(rows.length?' The highest-current-memory hosts can be reviewed directly in Host Inventory.':'');} if(evidence.forecast){const rows=evidence.forecast as Array<{host:string;peak:number|null;upper:number|null}>;return`Forecast results are available for ${rows.length} host(s). Peak forecast values reach up to ${Math.max(0,...rows.map(r=>r.peak??0)).toFixed(1)}%, with an upper-bound peak up to ${Math.max(0,...rows.map(r=>r.upper??0)).toFixed(1)}%.`;} if(evidence.grailQuery){const g=evidence.grailQuery as {dql:string;rows:RecordRow[]};if(!g.rows.length)return`The live Grail query returned no matching records for the selected scope.`;const sample=g.rows.slice(0,5).map(r=>Object.entries(r).map(([k,v])=>`${k}=${String(v)}`).join(', ')).join(' | ');return`The live Grail query returned ${g.rows.length} record(s). Sample evidence: ${sample}`;} return `I could not find enough live evidence to answer this question for the selected Management Zone (${context.managementZone}).`;}
async function synthesize(question:string,context:CapacityAiContext,evidence:Record<string,unknown>,previousState?:State):Promise<{answer:string;state?:State}>{const supplementary=`Selected Management Zone: ${context.managementZone}\nSelected data range: ${context.timeRange}\nForecast horizon: ${context.forecastHorizon} days\nLive host snapshot: ${JSON.stringify(compactHosts(context.hosts))}\nTool evidence: ${JSON.stringify(evidence).slice(0,MAX_SUPPLEMENTARY)}`;const response=await publicClient.recommenderConversation({body:{text:question,state:previousState,context:[{type:'supplementary',value:supplementary},{type:'instruction',value:'You are the Axis Bank Capacity Copilot. Answer the user question using only the supplied live/tool evidence. Never claim a value that is not in the evidence. Give the direct answer first, then 2-5 concise supporting points. This is a capacity-planning assistant, not a generic documentation chatbot.'}]}});const typed=response as {status?:string;text?:string;answer?:string;content?:string;state?:State};if(typed.status==='FAILED')throw new Error('Davis conversational synthesis failed.');const answer=String(typed.text??typed.answer??typed.content??'').trim();if(!answer)throw new Error('Davis conversational synthesis returned no answer.');return{answer,state:typed.state};}
export async function askAgenticDavisV52(question:string,context:CapacityAiContext,previousState?:State):Promise<CapacityAiResponse>{const q=question.trim();if(!q)throw new Error('Please enter a capacity-planning question.');const lower=q.toLowerCase();const evidence:Record<string,unknown>={};const growth=growthFrom(q);try{if(growth!==null)evidence.capacitySimulation=simulation(context.hosts,growth);if(/\b(problem|problems|incident|incidents|outage|outages)\b/i.test(q))evidence.davisProblems=await problemTool(context.hosts,daysFrom(q));else if(/closest|highest|top|risk|risky|cpu capacity|memory capacity|disk capacity/i.test(lower))evidence.capacityRiskSnapshot=riskSnapshot(context.hosts);else if(/primary capacity constraint|main capacity constraint|bottleneck|constrained resource/i.test(lower)){const a={cpu:avg(context.hosts,'cpu'),memory:avg(context.hosts,'memory'),disk:avg(context.hosts,'disk')};evidence.currentResourceAverages=a;evidence.primaryConstraint=Object.entries(a).sort((x,y)=>(y[1] as number)-(x[1] as number))[0];}else if(/memory trend|memory history|memory over|memory usage trend/i.test(lower))evidence.memoryTrend=await memoryTrendTool(context.hosts);else if(/forecast|predict|prediction|projected|future capacity|next \d+ days/i.test(lower))evidence.forecast=await forecastTool(context.hosts,context.forecastHorizon);else evidence.grailQuery=await arbitraryDqlTool(q,context.managementZone,context.hosts);}catch(error){evidence.toolError=error instanceof Error?error.message:String(error);} try{const result=await synthesize(q,context,evidence,previousState);return{answer:result.answer,state:result.state,mode:'tool-assisted'};}catch{const answer=evidenceForQuestion(context,evidence);return{answer,state:previousState,mode:'fallback'};}}
export const suggestedCapacityQuestions=['Which hosts are closest to CPU capacity?','What are the top capacity risks in this Management Zone?','What happens if traffic increases by 48%?','Which resource is the primary capacity constraint?','How many infrastructure problems were generated in the last 30 days?','What is the current memory trend for this Management Zone?','Summarize the capacity outlook for the next 30 days?'];
