const STYLE_ID='capacity-presentation-v47-style';
const FORECAST_ID='v46-forecast-svg';
const SIM_ID='simulation-combined-v46';
const COLORS={cpu:'#2f78df',memory:'#16a36b',disk:'#9b5de5'} as const;
type Metric='cpu'|'memory'|'disk';
const label=(m:Metric)=>m==='cpu'?'CPU':m==='memory'?'Memory':'Disk';

function installStyle(){if(document.getElementById(STYLE_ID))return;const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`.v46-sim-legend .v46-cpu{background:${COLORS.cpu}!important;color:${COLORS.cpu}!important}.v46-sim-legend .v46-memory{background:${COLORS.memory}!important;color:${COLORS.memory}!important}.v46-sim-legend .v46-disk{background:${COLORS.disk}!important;color:${COLORS.disk}!important}.v47-hover-guide{stroke:#718096;stroke-width:1;stroke-dasharray:3 3;pointer-events:none}`;document.head.appendChild(style)}
function tooltip(html:string,e:MouseEvent){let node=document.getElementById('capacity-v47-tooltip') as HTMLElement|null;if(!node){node=document.createElement('div');node.id='capacity-v47-tooltip';node.className='v46-tooltip';document.body.appendChild(node)}node.innerHTML=html;node.style.display='block';const w=node.offsetWidth||250,h=node.offsetHeight||110;let x=e.clientX+14,y=e.clientY-h-14;if(x+w>window.innerWidth)x=e.clientX-w-14;if(y<8)y=e.clientY+14;node.style.left=`${Math.max(8,x)}px`;node.style.top=`${Math.max(8,y)}px`}
function hide(){document.getElementById('capacity-v47-tooltip')?.style.setProperty('display','none')}
function points(poly:SVGPolylineElement|null){if(!poly)return[];return(poly.getAttribute('points')||'').trim().split(/\s+/).map(token=>{const [x,y]=token.split(',').map(Number);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}).filter((p):p is {x:number;y:number}=>!!p)}
function nearest(arr:Array<{x:number;y:number}>,x:number){if(!arr.length)return null;return arr.reduce((best,p)=>Math.abs(p.x-x)<Math.abs(best.x-x)?p:best,arr[0])}
function axisScale(svg:SVGSVGElement){const horizontal=[...svg.querySelectorAll<SVGLineElement>('.v46-grid')].filter(l=>l.getAttribute('y1')===l.getAttribute('y2')).map(l=>Number(l.getAttribute('y1'))).filter(Number.isFinite);const vertical=[...svg.querySelectorAll<SVGLineElement>('.v46-grid')].filter(l=>l.getAttribute('x1')===l.getAttribute('x2')&&l.getAttribute('y1')!==l.getAttribute('y2')).map(l=>Number(l.getAttribute('x1'))).filter(Number.isFinite);const y0=Math.max(...horizontal,270);const y100=Math.min(...horizontal,70);const splitX=vertical.length?vertical[0]:svg.viewBox.baseVal.width*.65;return{splitX,y0,y100,plotH:Math.max(1,y0-y100)}}
function parseDates(svg:SVGSVGElement){const text=[...svg.querySelectorAll('text')].map(n=>n.textContent?.trim()||'').join(' | ');const matches=[...text.matchAll(/(\d{1,2}\/\d{1,2}\/\d{4})/g)].map(m=>m[1]);const parsed=matches.map(s=>Date.parse(s)).filter(Number.isFinite);return{start:parsed[0]??Date.now()-30*86400000,end:parsed.at(-1)??Date.now()+30*86400000}}
function installForecastHover(){const svg=document.getElementById(FORECAST_ID) as SVGSVGElement|null;if(!svg||svg.dataset.v47Hover==='1')return;svg.dataset.v47Hover='1';const run=(e:MouseEvent)=>{const rect=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;const cursorX=((e.clientX-rect.left)/Math.max(1,rect.width))*vb.width;const scale=axisScale(svg);const metrics=['cpu','memory','disk'] as Metric[];const hist=metrics.map(m=>({m,pts:points(svg.querySelector<SVGPolylineElement>(`.v46-line-hist.v46-${m}`)),kind:'Historical'}));const fc=metrics.map(m=>({m,pts:points(svg.querySelector<SVGPolylineElement>(`.v46-line-fc.v46-${m}`)),kind:'Dynatrace Intelligence forecast'}));const histDist=Math.min(...hist.map(v=>v.pts.length?Math.abs(nearest(v.pts,cursorX)!.x-cursorX):Infinity));const fcDist=Math.min(...fc.map(v=>v.pts.length?Math.abs(nearest(v.pts,cursorX)!.x-cursorX):Infinity));const forecast=fcDist<Infinity&&fcDist<=Math.max(histDist,18);const selected=forecast?fc:hist;const basePts=selected.find(v=>v.pts.length)?.pts||[];if(!basePts.length)return;const basePoint=nearest(basePts,cursorX);if(!basePoint)return;const nearestX=basePoint.x;const values=selected.map(({m,pts})=>{const p=nearest(pts,nearestX);const value=p?Math.max(0,Math.min(100,(scale.y0-p.y)/scale.plotH*100)):null;return `${label(m)}: ${value===null?'—':`${value.toFixed(2)}%`}`}).join('<br>');const dateRange=parseDates(svg);let dateText='';if(forecast){const frac=basePts.length>1?Math.max(0,Math.min(1,basePts.indexOf(basePoint)/Math.max(1,basePts.length-1))):0;dateText=new Date(dateRange.end-(1-frac)*Math.max(1,dateRange.end-Date.now())).toLocaleString('en-IN')}else{const frac=basePts.length>1?Math.max(0,Math.min(1,basePts.indexOf(basePoint)/Math.max(1,basePts.length-1))):0;dateText=new Date(dateRange.start+frac*Math.max(1,Date.now()-dateRange.start)).toLocaleString('en-IN')}tooltip(`<strong>${dateText}</strong><span>${forecast?'Dynatrace Intelligence forecast':'Historical telemetry'}</span><b>${values}</b><small>Nearest rendered forecast bucket</small>`,e)};svg.addEventListener('mousemove',run);svg.addEventListener('mouseleave',hide)}
function fixSimulationLegend(){document.querySelectorAll<HTMLElement>(`#${SIM_ID} .v46-sim-legend i`).forEach(node=>{const cls=(node.className||'').toString();const m=(['cpu','memory','disk'] as Metric[]).find(k=>cls.split(/\s+/).includes(`v46-${k}`));if(m)node.style.background=COLORS[m]})}
export function installCapacityPresentationV47(){installStyle();const apply=()=>{installForecastHover();fixSimulationLegend()};apply();document.addEventListener('click',()=>window.setTimeout(apply,120));document.addEventListener('change',()=>window.setTimeout(apply,120));window.setInterval(apply,1000)}
