import { analyzersClient } from '@dynatrace-sdk/client-davis-analyzers';
import { queryExecutionClient } from '@dynatrace-sdk/client-query';
import type { ForecastHorizon, Host, MetricKey } from '@/types';
import type { DynatraceForecast } from './dynatraceIntelligence';

const ANALYZER = 'dt.statistics.GenericForecastAnalyzer';
const metricName = (metric: MetricKey) => metric === 'cpu' ? 'dt.host.cpu.usage' : metric === 'memory' ? 'dt.host.memory.usage' : 'dt.host.disk.used.percent';
const numeric = (value: unknown): number | undefined => { if (typeof value === 'number' && Number.isFinite(value)) return value; if (typeof value === 'string' && value.trim()) { const n = Number(value); return Number.isFinite(n) ? n : undefined; } if (Array.isArray(value)) { for (let i = value.length - 1; i >= 0; i -= 1) { const n = numeric(value[i]); if (n !== undefined) return n; } } if (value && typeof value === 'object') { const object = value as Record<string, unknown>; return numeric(object.values ?? object.data ?? object.value ?? object.number); } return undefined; };
const series = (value: unknown): number[] => Array.isArray(value) ? value.map((item) => numeric(item)).filter((item): item is number => item !== undefined) : numeric(value) === undefined ? [] : [numeric(value)!];
const escape = (value: string) => value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
async function queryHistory(queryText: string): Promise<Record<string, unknown>[]> { const response = await queryExecutionClient.queryExecute({ body: { query: queryText, requestTimeoutMilliseconds: 30000, maxResultRecords: 1000 } }); let result = response.result as { records?: Array<Record<string, unknown> | null> } | undefined; const token = response.requestToken; let state = response.state; for (let attempt = 0; !result && token && attempt < 30; attempt += 1) { const polled = await queryExecutionClient.queryPoll({ requestToken: token, requestTimeoutMilliseconds: 30000 }); state = polled.state; result = polled.result as { records?: Array<Record<string, unknown> | null> } | undefined; if (!result && state === 'RUNNING') await new Promise((resolve) => setTimeout(resolve, 300)); } if (!result) throw new Error(`Forecast history query did not return a result (state: ${state}).`); return (result.records ?? []).filter(Boolean) as Record<string, unknown>[]; }
async function poll(requestToken: string) { for (let attempt = 0; attempt < 25; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 600)); const response = await analyzersClient.pollAnalyzerExecution({ analyzerName: ANALYZER, requestToken, timeoutSeconds: 5 }); if (response.result.executionStatus === 'COMPLETED') return response.result; if (response.result.executionStatus === 'ABORTED') throw new Error('Dynatrace Intelligence forecast was aborted.'); } throw new Error('Dynatrace Intelligence forecast timed out.'); }
export async function runEnhancedForecast(host: Host, metric: MetricKey, horizon: ForecastHorizon): Promise<DynatraceForecast> { const expression = `timeseries value=avg(${metricName(metric)}), interval:6h, from:-30d, to:now(), filter:in(dt.entity.host, "${escape(host.id)}")`; let historical: number[] = []; try { const history = await queryHistory(`${expression} | fields value`); historical = series(history[0]?.value); const response = await analyzersClient.executeAnalyzer({ analyzerName: ANALYZER, timeoutSeconds: 5, body: { timeSeriesData: { expression }, forecastHorizon: horizon * 4, coverageProbability: 0.9, nPaths: 200 } }); const result = response.requestToken ? await poll(response.requestToken) : response.result; const output = result.output?.[0] as Record<string, any> | undefined; const band = output?.timeSeriesDataWithPredictions?.records?.[0] as Record<string, any> | undefined; if (!band || result.resultStatus === 'FAILED') throw new Error(output?.analysisStatus || result.logs?.map((entry: any) => entry.message).join(' ') || 'Forecast analyzer returned no prediction.'); const point = series(band['dt.davis.forecast:point']); const lower = series(band['dt.davis.forecast:lower']); const upper = series(band['dt.davis.forecast:upper']); const timeframe = band.timeframe as { start?: string; end?: string } | undefined; return { metric, horizon, historical, forecast: point, lowerBound: lower, upperBound: upper, forecastStart: timeframe?.start ?? null, forecastEnd: timeframe?.end ?? null, quality: String(output?.forecastQualityAssessment ?? 'unknown'), status: String(output?.analysisStatus ?? 'OK'), source: 'Dynatrace Intelligence' }; } catch (error) { return { metric, horizon, historical, forecast: [], lowerBound: [], upperBound: [], forecastStart: null, forecastEnd: null, quality: 'unavailable', status: 'FAILED', source: 'fallback', error: error instanceof Error ? error.message : String(error) }; } }
export async function getEnhancedForecasts(hosts: Host[], metric: MetricKey, horizon: ForecastHorizon) { return Promise.all(hosts.map(async (host) => ({ host, forecast: await runEnhancedForecast(host, metric, horizon) })));
}
