import { dynatraceDataProvider } from './realDynatrace';
import { askAgenticDavisV52, suggestedCapacityQuestions, type CapacityAiContext } from './agenticCapacityAiV51';
import type { State } from '@dynatrace-sdk/client-davis-copilot';
import type { ForecastHorizon, TimeRange } from '@/types';

const ID='axis-davis-interactive-ai-v47';
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const getScope=()=>{const selects=[...document.querySelectorAll<HTMLSelectElement>('.top-actions select')];const zone=selects.find(s=>[...s.options].some(o=>o.textContent?.trim()==='All Management Zones'))?.value||'All Management Zones';const range=(selects.find(s=>['1h','6h','24h','7d','30d'].includes(s.value))?.value||'24h') as TimeRange;const horizon=Number(selects.find(s=>['7','14','30','60','90'].includes(s.value))?.value||30) as ForecastHorizon;return{zone,range,horizon};};

export function installInteractiveCapacityAiV47(){
  if(document.getElementById(ID))return;
  const root=document.createElement('section');root.id=ID;root.className='panel axis-davis-ai-panel';
  root.innerHTML=`<div class="axis-davis-ai-head"><div><span class="eyebrow">Davis Intelligence</span><h2>Ask Davis about capacity</h2><p>Ask natural-language questions about the selected Axis Bank Management Zone. Davis can use live Dynatrace telemetry, read-only Grail/DQL evidence, forecast analysis and what-if simulation.</p></div><span class="axis-davis-ai-badge">Interactive AI</span></div><div class="axis-davis-ai-suggestions">${suggestedCapacityQuestions.slice(0,5).map(q=>`<button type="button" data-q="${esc(q)}">${esc(q)}</button>`).join('')}</div><div class="axis-davis-ai-input"><textarea rows="3" placeholder="Ask any capacity-planning question..."></textarea><button type="button" data-ask>Ask Davis</button></div><div class="axis-davis-ai-status" data-status></div><div class="axis-davis-ai-answer" data-answer hidden></div>`;
  const mount=()=>{if(document.getElementById(ID))return;const overview=[...document.querySelectorAll('h1')].find(h=>h.textContent?.includes('Capacity at a glance'))?.closest('.content');if(!overview)return;const anchor=overview.querySelector('.overview-grid');if(anchor?.parentElement)anchor.parentElement.insertBefore(root,anchor.nextSibling);};
  mount();const observer=new MutationObserver(mount);observer.observe(document.body,{childList:true,subtree:true});
  const textarea=root.querySelector('textarea') as HTMLTextAreaElement;const status=root.querySelector('[data-status]') as HTMLElement;const answer=root.querySelector('[data-answer]') as HTMLElement;const askButton=root.querySelector('[data-ask]') as HTMLButtonElement;
  root.querySelectorAll<HTMLButtonElement>('[data-q]').forEach(button=>button.addEventListener('click',()=>{textarea.value=button.dataset.q??'';textarea.focus();}));
  const ask=async()=>{const question=textarea.value.trim();if(!question){status.textContent='Enter a capacity-planning question first.';return;}askButton.disabled=true;answer.hidden=true;const scope=getScope();status.textContent='Davis is selecting the right capacity tools…';try{const hosts=await dynatraceDataProvider.getHosts(scope.zone,scope.range);if(!hosts.length)throw new Error('No hosts are available for the selected Management Zone.');status.textContent=`Using ${hosts.length} live hosts from ${scope.zone}…`;const previousState=(window as Window & {__axisDavisState?:State}).__axisDavisState;const context:CapacityAiContext={managementZone:scope.zone,timeRange:scope.range,forecastHorizon:scope.horizon,hosts,forecasts:[]};const result=await askAgenticDavisV52(question,context,previousState);answer.innerHTML=esc(result.answer).replace(/\n/g,'<br/>');answer.hidden=false;(window as Window & {__axisDavisLastQa?:{question:string;answer:string}}).__axisDavisLastQa={question,answer:result.answer};if(result.state)(window as Window & {__axisDavisState?:State}).__axisDavisState=result.state;window.dispatchEvent(new CustomEvent('axis-davis-answer',{detail:{question,answer:result.answer,mode:result.mode}}));status.textContent=`Davis ${result.mode==='tool-assisted'?'tool-assisted':'evidence fallback'} answer · ${new Date().toLocaleTimeString()}`;}catch(error){status.textContent=`Davis could not complete the assessment: ${error instanceof Error?error.message:String(error)}`;}finally{askButton.disabled=false;}};
  askButton.addEventListener('click',ask);textarea.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter')void ask();});
}
