import { dynatraceDataProvider } from './realDynatrace';
import type { Host, TimeRange } from '@/types';

const STYLE_ID = 'overview-risk-v43-style';
const MODAL_ID = 'overview-risk-v43-modal';
const finite = (v: number | undefined | null) => typeof v === 'number' && Number.isFinite(v) ? v : 0;
const esc = (v: string) => v.replace(/[&<>\"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#39;' }[c] ?? c));
const riskScore = (h: Host) => Math.max(finite(h.telemetry.at(-1)?.cpu), finite(h.telemetry.at(-1)?.memory), finite(h.telemetry.at(-1)?.disk));
const status = (h: Host) => { const s = riskScore(h); return s >= 90 ? 'Critical' : s >= 70 ? 'High Risk' : 'Healthy / Stable'; };
function injectStyles() { if (document.getElementById(STYLE_ID)) return; const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = `.overview-risk-card{cursor:pointer!important;transition:transform .15s ease,box-shadow .15s ease}.overview-risk-card:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(20,50,90,.12)}#${MODAL_ID}{position:fixed;inset:0;background:rgba(12,28,49,.42);z-index:2147483000;display:flex;align-items:center;justify-content:center;padding:24px}#${MODAL_ID} .risk-dialog{width:min(1080px,96vw);max-height:88vh;overflow:auto;background:#fff;border-radius:14px;box-shadow:0 28px 80px rgba(10,30,55,.28);padding:20px}#${MODAL_ID} .risk-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;border-bottom:1px solid #e6ebf1;padding-bottom:14px;margin-bottom:12px}#${MODAL_ID} .risk-head h2{margin:0;font-size:18px;color:#17365d}#${MODAL_ID} .risk-head p{margin:4px 0 0;font-size:11px;color:#6a7a90}#${MODAL_ID} button{border:1px solid #d1dbe7;background:#f8fafc;border-radius:8px;padding:7px 10px;cursor:pointer;color:#17365d;font-weight:700}#${MODAL_ID} .risk-table{overflow:auto}#${MODAL_ID} table{width:100%;border-collapse:collapse}#${MODAL_ID} th,#${MODAL_ID} td{padding:9px 8px;border-bottom:1px solid #edf1f5;text-align:left;font-size:11px}#${MODAL_ID} th{font-size:10px;text-transform:uppercase;color:#74849a}#${MODAL_ID} td strong{display:block;color:#17365d}#${MODAL_ID} td small{display:block;color:#8190a4;margin-top:2px}#${MODAL_ID} .risk-pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#f9ecea;color:#ad443d;font-size:9px;font-weight:800}#${MODAL_ID} .risk-pill.high{background:#fff1dd;color:#a86100}#${MODAL_ID} .risk-empty{padding:35px;text-align:center;color:#708197}.dark #${MODAL_ID} .risk-dialog{background:#172235;color:#e5edf8}.dark #${MODAL_ID} .risk-head{border-color:#33465f}.dark #${MODAL_ID} .risk-head h2,.dark #${MODAL_ID} td strong{color:#e5edf8}.dark #${MODAL_ID} .risk-head p,.dark #${MODAL_ID} th,.dark #${MODAL_ID} td small{color:#b9c7d8}.dark #${MODAL_ID} button{background:#111827;border-color:#33465f;color:#e5edf8}`; document.head.appendChild(style); }
async function showDetails(kind: 'high'|'critical') { const selects=[...document.querySelectorAll<HTMLSelectElement>('.mz-selector select')]; const zone=selects[0]?.value || 'All Management Zones'; const range=(selects[1]?.value || '24h') as TimeRange; const modal=document.createElement('div'); modal.id=MODAL_ID; modal.innerHTML=`<div class="risk-dialog"><div class="risk-head"><div><h2>${kind==='critical'?'Critical hosts':'High-risk hosts'}</h2><p>Live Dynatrace host telemetry · ${esc(zone)} · ${esc(range)}</p></div><button type="button" data-risk-close>Close</button></div><div class="risk-table"><div class="risk-empty">Loading live host details…</div></div></div>`; document.body.appendChild(modal); modal.querySelector('[data-risk-close]')?.addEventListener('click',()=>modal.remove()); modal.addEventListener('click',(e)=>{if(e.target===modal)modal.remove();}); try { const hosts=await dynatraceDataProvider.getHosts(zone,range); const wanted=hosts.filter((h)=>kind==='critical'?status(h)==='Critical':status(h)==='High Risk').sort((a,b)=>riskScore(b)-riskScore(a)); const body=modal.querySelector('.risk-table')!; body.innerHTML=wanted.length?`<table><thead><tr><th>Host</th><th>Application / Host Group</th><th>CPU</th><th>Memory</th><th>Disk</th><th>Peak</th><th>Status</th></tr></thead><tbody>${wanted.map((h)=>{const p=h.telemetry.at(-1);const cpu=finite(p?.cpu),memory=finite(p?.memory),disk=finite(p?.disk),score=Math.max(cpu,memory,disk);return `<tr><td><strong>${esc(h.name)}</strong><small>${esc(h.id)}</small></td><td>${esc(h.application)}</td><td>${cpu.toFixed(1)}%</td><td>${memory.toFixed(1)}%</td><td>${disk.toFixed(1)}%</td><td>${score.toFixed(1)}%</td><td><span class="risk-pill ${kind==='high'?'high':''}">${status(h)}</span></td></tr>`;}).join('')}</tbody></table>`:`<div class="risk-empty">No ${kind==='critical'?'critical':'high-risk'} hosts were returned for the current scope.</div>`; } catch(error) { modal.querySelector('.risk-table')!.innerHTML=`<div class="risk-empty">Unable to load live host details: ${esc(error instanceof Error?error.message:String(error))}</div>`; } }
export function installOverviewRiskDrilldownV43() { const w=window as Window & {__overviewRiskV43?:boolean}; if(w.__overviewRiskV43)return; w.__overviewRiskV43=true; injectStyles(); const refresh=()=>{if(![...document.querySelectorAll('.nav-item.active span')].some((n)=>n.textContent?.trim()==='Overview'))return; document.querySelectorAll<HTMLElement>('.metric-card').forEach((card)=>{const text=card.innerText||''; if(/High Risk/i.test(text)&&!/Critical/i.test(text)){card.classList.add('overview-risk-card');card.dataset.riskKind='high';} if(/Critical/i.test(text)){card.classList.add('overview-risk-card');card.dataset.riskKind='critical';}});}; document.addEventListener('click',(e)=>{const target=e.target instanceof Element?e.target.closest<HTMLElement>('.overview-risk-card'):null; if(target?.dataset.riskKind) { e.preventDefault(); e.stopPropagation(); void showDetails(target.dataset.riskKind as 'high'|'critical'); }}); document.addEventListener('click',()=>window.setTimeout(refresh,250)); window.setInterval(refresh,1000); window.setTimeout(refresh,700); }
