import { jsPDF } from 'jspdf';

type Snap = { page: string; metric?: string; title?: string; unit?: string; svgs: SVGSVGElement[]; text: string };
const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
async function waitFor(test: () => boolean, timeout = 60000) { const started = Date.now(); while (Date.now() - started < timeout) { if (test()) return true; await sleep(300); } return false; }
function nav(name: string) { [...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find((b) => b.innerText.trim() === name)?.click(); }
function pageName() { return document.querySelector('.nav-item.active')?.textContent?.trim() || ''; }
function textOf(e: Element | null) { return e?.textContent?.replace(/\s+/g, ' ').trim() || ''; }
function currentMetric() { const s = [...document.querySelectorAll<HTMLSelectElement>('select')].find((x) => /metric/i.test(x.previousElementSibling?.textContent || '') || ['cpu','memory','disk','networkRx','networkTx','throughput'].includes(x.value)); return s?.value || ''; }
function metricMeta(key: string) { const m: Record<string,[string,string]> = { cpu:['CPU utilization','%'], memory:['Memory utilization','%'], disk:['Disk utilization','%'], networkRx:['Network RX','B/s'], networkTx:['Network TX','B/s'], throughput:['Application throughput','req/min'] }; return m[key] || ['Metric','value']; }
function labelDom(key: string) { const [name, unit] = metricMeta(key); document.querySelectorAll<HTMLElement>('.chart-panel').forEach((p) => { const row = p.querySelector('.chart-title-row'); if (row) { row.querySelector('strong')!.textContent = `${name} (${unit})`; row.querySelector('span')!.textContent = `Unit: ${unit} · X-axis: Date / time · Hover for exact value`; } }); }
function snap(): Snap { const key = currentMetric(); const [name, unit] = metricMeta(key); const svgs = [...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg, .forecast-band-wrap svg, .projection-svg')]; return { page: pageName(), metric: key, title: name, unit, svgs, text: document.body.innerText }; }
async function setMetric(key: string) { const s = [...document.querySelectorAll<HTMLSelectElement>('select')].find((x) => ['cpu','memory','disk','networkRx','networkTx','throughput'].includes(x.value) || /metric/i.test(x.previousElementSibling?.textContent || '')); if (!s) return; s.value = key; s.dispatchEvent(new Event('input',{bubbles:true})); s.dispatchEvent(new Event('change',{bubbles:true})); await sleep(800); labelDom(key); await waitFor(() => Boolean(document.querySelector('.chart-wrap svg')), 10000); }
function svgPng(svg: SVGSVGElement, width = 1000, height = 360) { const clone = svg.cloneNode(true) as SVGSVGElement; clone.setAttribute('width', String(width)); clone.setAttribute('height', String(height)); clone.setAttribute('xmlns','http://www.w3.org/2000/svg'); const style = document.createElementNS('http://www.w3.org/2000/svg','style'); style.textContent = `.chart-grid{stroke:#dfe6ef;stroke-width:1}.chart-line.actual{fill:none;stroke:#327fe6;stroke-width:3}.chart-line.forecast{fill:none;stroke:#e88b32;stroke-width:3;stroke-dasharray:7 5}.forecast-band{fill:rgba(231,159,41,.18)}.threshold-line{stroke:#d55d4b;stroke-width:1.5;stroke-dasharray:5 4}.chart-axis-label,.chart-axis-title,.threshold-label,.projection-label,.scenario-start-label,.scenario-end-label{font-family:Arial,sans-serif;font-size:11px;fill:#4d6078}.projection-line{fill:none;stroke:#327fe6;stroke-width:3}.projection-point{fill:#fff;stroke:#327fe6;stroke-width:2}.scenario-line.forecast{fill:none;stroke:#e88b32;stroke-width:3}`; clone.insertBefore(style, clone.firstChild); return new Promise<string>((resolve,reject)=>{ const img=new Image(); img.onload=()=>{const c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');if(!ctx)return reject(new Error('Canvas unavailable'));ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);resolve(c.toDataURL('image/png'));};img.onerror=()=>reject(new Error('SVG rasterization failed'));img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(clone)); }); }
function wrap(doc: jsPDF, value: string, x: number, y: number, width: number, size=8, lead=11) { doc.setFontSize(size); const lines=doc.splitTextToSize(value,width); doc.text(lines,x,y); return y+lines.length*lead; }
async function addChart(doc:jsPDF,svg:SVGSVGElement,title:string,unit:string,x:number,y:number,w:number,h:number){doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(title,x,y);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${unit}`,x+w-90,y);try{doc.addImage(await svgPng(svg,1000,Math.max(260,Math.round(h*2.4))),'PNG',x,y+7,w,h-10,undefined,'FAST');}catch{doc.setFontSize(8);doc.text('Chart rendering unavailable.',x,y+25);}}
function header(doc:jsPDF,title:string,subtitle:string){doc.setTextColor(20,35,56);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES',40,32);doc.setFontSize(18);doc.text(title,40,53);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(subtitle,40,66);doc.text(`Generated ${new Date().toLocaleString('en-IN')}`,40,78);}
async function collect(){const out:Snap[]=[];nav('Overview');await sleep(1000);const aiButton=[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>/Generate AI Assessment/i.test(b.innerText));if(aiButton)aiButton.click();await waitFor(()=>{const t=document.querySelector<HTMLElement>('.ai-assessment');return Boolean(t?.innerText && !/Analyzing|Generate prioritized/i.test(t.innerText));},45000);out.push(snap());nav('Host Inventory');await sleep(900);const row=document.querySelector<HTMLTableRowElement>('tbody tr');if(row){row.click();await sleep(1000);for(const key of ['throughput','cpu','memory','disk','networkRx','networkTx']){await setMetric(key);out.push(snap());}}nav('Capacity Forecast');await sleep(1200);const run=[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>/Run .*forecast/i.test(b.innerText));if(run)run.click();await waitFor(()=>Boolean(document.querySelector('.forecast-band-wrap svg')),45000);out.push(snap());nav('Simulation');await sleep(1200);await waitFor(()=>document.querySelectorAll('.projection-svg').length>=3,60000);out.push(snap());return out;}
async function build(snaps:Snap[]){const doc=new jsPDF({unit:'pt',format:'a4'});const overview=snaps.find(s=>/Overview/i.test(s.page))||snaps[0];header(doc,'Executive Capacity Report','Live Dynatrace capacity planning snapshot');let y=108;const cards=[...document.querySelectorAll<HTMLElement>('.metric-card')].slice(0,8).map(e=>textOf(e)).filter(Boolean);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Capacity at a glance',40,y);y+=18;for(const c of cards){y=wrap(doc,c,40,y,515,8,11)+3;}const ai=document.querySelector<HTMLElement>('.ai-assessment')?.innerText?.trim()||'AI assessment was not available during report generation.';doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('AI-assisted capacity assessment',40,Math.max(y+18,330));y=Math.max(y+36,348);for(const line of ai.split(/\n+/).filter(Boolean).slice(0,20)){if(y>770)break;y=wrap(doc,line,40,y,515,8,11)+2;}
const host=snaps.filter(s=>/Host Inventory/i.test(s.page));doc.addPage();header(doc,'Infrastructure Trend Analysis','Metric labels, units and date/time axes are explicitly identified.');y=105;for(const s of host){const svg=s.svgs.find(v=>v.closest('.chart-panel'));if(!svg)continue;const [name,unit]=metricMeta(s.metric||'');if(y>650){doc.addPage();header(doc,'Infrastructure Trend Analysis','Continued infrastructure trends.');y=105;}await addChart(doc,svg,name,unit,48,y,500,105);y+=118;}
const fc=snaps.find(s=>/Capacity Forecast/i.test(s.page));doc.addPage();header(doc,'Dynatrace Forecast','Historical telemetry plus real Dynatrace Intelligence forecast when returned.');const fsvg=fc?.svgs.find(v=>v.closest('.forecast-band-wrap'));if(fsvg){await addChart(doc,fsvg,'Capacity forecast',fc?.unit||'%',48,110,500,300);doc.setFontSize(8);doc.text(fc?.text.includes('90% prediction interval')?'90% prediction interval displayed.':'Forecast chart captured from the live application.',48,425);}else{doc.setFontSize(10);doc.text('No forecast chart was rendered by Dynatrace for this run. Historical telemetry is not fabricated into a forecast.',48,130);}
const sim=snaps.find(s=>/Simulation/i.test(s.page));doc.addPage();header(doc,'Traffic What-if & Resource Capacity','Scenario impact with explicit 20 / 60 / 90-day resource checkpoints.');y=105;const detail=document.querySelector<HTMLElement>('.simulation-scenario-detail')?.innerText?.trim()||'';if(detail)y=wrap(doc,detail,48,y,500,8,11)+12;const psvgs=sim?.svgs.filter(v=>v.classList.contains('projection-svg'))||[];for(const svg of psvgs){if(y>620){doc.addPage();header(doc,'Traffic What-if & Resource Capacity','Continued resource projections.');y=105;}const aria=svg.getAttribute('aria-label')||'';const name=/memory/i.test(aria)?'Memory utilization':/disk/i.test(aria)?'Disk utilization':'CPU utilization';await addChart(doc,svg,name,'%',48,y,500,175);y+=190;}
if(!psvgs.length){doc.setFontSize(10);doc.text('Resource projection charts did not finish rendering before PDF capture.',48,130);}
doc.addPage();header(doc,'AI Recommendations','Prioritized recommendations captured from the live application.');y=110;for(const line of ai.split(/\n+/).filter(Boolean)){if(y>770){doc.addPage();header(doc,'AI Recommendations','Continued recommendations.');y=105;}y=wrap(doc,line,48,y,500,9,13)+3;}doc.save('axis-capacity-report.pdf');}
export function installProductionPdfV3(){const state=window as Window & {__axisProductionPdfV3?:boolean};if(state.__axisProductionPdfV3)return;state.__axisProductionPdfV3=true;document.addEventListener('click',async(e)=>{const b=e.target instanceof Element?e.target.closest('.pdf-report-button'):null;if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{await build(await collect());}catch(err){console.error(err);alert(`PDF generation failed: ${err instanceof Error?err.message:String(err)}`);}},true);}
