import { jsPDF } from 'jspdf';

type Point = { day: number; value: number };
type Chart = { title: string; unit: string; svg: SVGSVGElement; context: 'history' | 'forecast' | 'simulation' };
type Kpi = { label: string; value: string; detail: string };
type Host = { host: string; environment: string; application: string; cpu: string; memory: string; disk: string; throughput: string; status: string };
type Simulation = { growth: number; currentTraffic: number; targetTraffic: number; projections: Record<string, Point[]> } | null;
type Report = { generated: string; zone: string; range: string; horizon: string; kpis: Kpi[]; ai: string; findings: string[]; charts: Chart[]; forecastChart?: Chart; hosts: Host[]; simulation: Simulation };

const C = { navy: [22, 41, 67] as const, blue: [44, 103, 180] as const, teal: [32, 132, 125] as const, amber: [206, 137, 34] as const, red: [190, 74, 65] as const, text: [37, 49, 66] as const, muted: [95, 109, 128] as const, border: [214, 222, 232] as const, light: [247, 249, 252] as const, white: [255, 255, 255] as const };
const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const txt = (e: Element | null | undefined) => e?.textContent?.replace(/\s+/g, ' ').trim() || '';
const num = (s: string) => Number((s || '').replace(/,/g, '').match(/-?\d+(?:\.\d+)?/)?.[0] || 0);
const active = () => document.querySelector('.nav-item.active')?.textContent?.trim() || '';
const nav = (name: string) => [...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find((b) => b.innerText.trim() === name)?.click();
async function waitFor(test: () => boolean, timeout = 30000) { const start = Date.now(); while (Date.now() - start < timeout) { if (test()) return true; await sleep(250); } return false; }
function metricMeta(panel: Element): [string, string] { const t = txt(panel.querySelector('h2,.chart-title-row strong')).toLowerCase(); if (t.includes('memory')) return ['Memory utilization', '%']; if (t.includes('disk')) return ['Disk utilization', '%']; if (t.includes('network rx')) return ['Network RX', 'B/s']; if (t.includes('network tx')) return ['Network TX', 'B/s']; if (t.includes('throughput')) return ['Application throughput', 'req/min']; return ['CPU utilization', '%']; }
function context(svg: SVGSVGElement): Chart['context'] { if (svg.classList.contains('projection-svg') || svg.closest('.projection-card')) return 'simulation'; if (svg.closest('.forecast-panel')) return 'forecast'; return 'history'; }
function charts(): Chart[] { return [...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg,.forecast-band-wrap svg,.projection-svg')].map((svg) => { const panel = svg.closest('.chart-panel,.projection-card,.forecast-panel,.forecast-band-wrap') || svg.parentElement; const [title, unit] = metricMeta(panel || svg); return { title, unit, svg: svg.cloneNode(true) as SVGSVGElement, context: context(svg) }; }); }
function kpis(): Kpi[] { return [...document.querySelectorAll<HTMLElement>('.metric-card')].map((c) => ({ label: txt(c.querySelector('p')), value: txt(c.querySelector('strong')), detail: txt(c.querySelector('small')) })).filter((k) => k.label && k.value).slice(0, 10); }
function ai(): string { return txt(document.querySelector('.ai-summary pre')) || txt(document.querySelector('.ai-summary')); }
function hosts(): Host[] { return [...document.querySelectorAll<HTMLTableRowElement>('table tbody tr')].map((r) => { const c = [...r.cells].map(txt); return { host: c[0] || '—', environment: c[1] || '—', application: c[2] || '—', cpu: c[3] || '—', memory: c[4] || '—', disk: c[5] || '—', throughput: c[6] || '—', status: c[7] || c.at(-1) || '—' }; }).filter((h) => h.host !== '—'); }
function simulation(): Simulation { const detail = document.querySelector<HTMLElement>('.simulation-scenario-detail'); const cards = [...document.querySelectorAll<HTMLElement>('.scenario-assumptions div')].map(txt); if (!detail && !document.querySelector('.projection-card')) return null; const growth = num(txt(detail?.querySelector('.projection-header h2') || null)); const current = num(cards.find((x) => /Current traffic/i.test(x)) || ''); const target = num(cards.find((x) => /Scenario traffic/i.test(x)) || ''); const projections: Record<string, Point[]> = {}; document.querySelectorAll<HTMLElement>('.projection-card').forEach((card) => { const name = txt(card.querySelector('.chart-title-row strong')) || 'Resource'; projections[name] = [...card.querySelectorAll<SVGCircleElement>('circle')].map((c) => ({ day: num(c.getAttribute('data-day') || ''), value: num(c.getAttribute('data-value') || '') })).filter((p) => Number.isFinite(p.value)).sort((a, b) => a.day - b.day); }); return { growth, currentTraffic: current, targetTraffic: target, projections }; }
function state(): Report { const selects = [...document.querySelectorAll<HTMLSelectElement>('select')]; const zone = selects.find((s) => /management zone/i.test(s.previousElementSibling?.textContent || ''))?.value || 'All Management Zones'; const range = selects.find((s) => /current data/i.test(s.previousElementSibling?.textContent || ''))?.value || 'Current window'; const horizon = selects.find((s) => /forecast/i.test(s.previousElementSibling?.textContent || ''))?.value || '30'; const all = charts(); return { generated: new Date().toLocaleString('en-IN'), zone, range, horizon: `${horizon} days`, kpis: kpis(), ai: ai(), findings: [], charts: all.filter((c) => c.context === 'history'), forecastChart: all.find((c) => c.context === 'forecast'), hosts: hosts(), simulation: simulation() }; }
async function ensureAi() { if (ai()) return; nav('Overview'); await sleep(600); const b = document.querySelector<HTMLButtonElement>('.ai-panel .ai-button'); if (b && !b.disabled) b.click(); await waitFor(() => Boolean(ai()), 45000); }
async function ensureForecast() { nav('Capacity Forecast'); await sleep(600); if (document.querySelector('.forecast-panel svg')) return; const b = [...document.querySelectorAll<HTMLButtonElement>('button')].find((x) => /Run .*forecast/i.test(x.innerText)); if (b) b.click(); await waitFor(() => Boolean(document.querySelector('.forecast-panel svg')), 45000); }
async function setMetric(key: string) { const s = [...document.querySelectorAll<HTMLSelectElement>('select')].find((x) => ['throughput', 'cpu', 'memory', 'disk', 'networkRx', 'networkTx'].includes(x.value)); if (!s) return; s.value = key; s.dispatchEvent(new Event('change', { bubbles: true })); await waitFor(() => Boolean(document.querySelector('.chart-wrap svg')), 7000); }
async function collect(): Promise<Report> { nav('Overview'); await sleep(600); const base = state(); await ensureForecast(); const forecastState = state(); nav('Host Inventory'); await sleep(650); const hostRows = hosts(); const hCharts: Chart[] = []; const first = document.querySelector<HTMLTableRowElement>('table tbody tr'); if (first) { first.click(); await sleep(650); for (const key of ['throughput', 'cpu', 'memory', 'disk', 'networkRx', 'networkTx']) { await setMetric(key); hCharts.push(...charts().filter((c) => c.context === 'history').slice(-1)); } }
  await ensureAi(); nav('Simulation'); await sleep(650); await waitFor(() => document.querySelectorAll('.projection-card,.projection-svg').length >= 3, 25000); const simState = state(); const s = simState.simulation; const findings: string[] = []; const avg = (index: number) => hostRows.length ? hostRows.reduce((sum, h) => sum + num([h.cpu, h.memory, h.disk][index]), 0) / hostRows.length : 0; const acpu = avg(0), amem = avg(1), adip = avg(2); findings.push(`Current estate contains ${hostRows.length} host(s) with average CPU ${acpu.toFixed(1)}%, memory ${amem.toFixed(1)}% and disk ${adip.toFixed(1)}%.`); if (acpu >= 80 || amem >= 80 || adip >= 80) findings.push('At least one estate resource is currently at or above the 80% planning threshold and should be prioritised for capacity review.'); else findings.push('Average estate utilization is below the 80% planning threshold in the captured inventory state.'); if (s) findings.push(`The active what-if scenario models ${s.growth.toFixed(1)}% traffic growth from ${s.currentTraffic.toFixed(1)} req/min to ${s.targetTraffic.toFixed(1)} req/min.`); if (forecastState.forecastChart) findings.push('A Dynatrace Intelligence forecast was captured from the Capacity Forecast page.'); else findings.push('No rendered Dynatrace Intelligence forecast was available at report capture time.'); const r = { ...base, ai: ai(), hosts: hostRows, charts: hCharts, forecastChart: forecastState.forecastChart, simulation: s, findings }; return r; }
function wrap(doc: jsPDF, text: string, x: number, y: number, width: number, size = 8.5, lead = 12) { doc.setFontSize(size); const lines = doc.splitTextToSize(text, width); doc.text(lines, x, y); return y + lines.length * lead; }
function header(doc: jsPDF, report: Report, title: string, sub = '') { doc.setFillColor(...C.navy); doc.rect(0, 0, 595, 82, 'F'); doc.setTextColor(...C.white); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES', 38, 26); doc.setFontSize(19); doc.text(title, 38, 49); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.text(sub || `${report.zone} · ${report.range} · ${report.horizon}`, 38, 66); doc.text(report.generated, 557, 26, { align: 'right' }); }
function footer(doc: jsPDF, page: number, total: number) { doc.setDrawColor(...C.border); doc.line(38, 790, 557, 790); doc.setTextColor(...C.muted); doc.setFontSize(7); doc.text('Axis Davis Capacity Planner · Live Dynatrace telemetry · Management planning report', 38, 805); doc.text(`${page} / ${total}`, 557, 805, { align: 'right' }); }
function card(doc: jsPDF, x: number, y: number, w: number, h: number, k: Kpi, tone: readonly [number, number, number] = C.blue) { doc.setFillColor(...C.white); doc.setDrawColor(...C.border); doc.roundedRect(x, y, w, h, 7, 7, 'FD'); doc.setFillColor(...tone); doc.rect(x, y, 4, h, 'F'); doc.setTextColor(...C.muted); doc.setFontSize(7); doc.text(k.label, x + 12, y + 16); doc.setTextColor(...C.navy); doc.setFont('helvetica', 'bold'); doc.setFontSize(15); doc.text(k.value, x + 12, y + 36); doc.setFont('helvetica', 'normal'); doc.setTextColor(...C.muted); doc.setFontSize(7); doc.text(doc.splitTextToSize(k.detail, w - 20).slice(0, 2), x + 12, y + 49); }
function table(doc: jsPDF, x: number, y: number, widths: number[], headers: string[], rows: string[][], rowH = 18) { const total = widths.reduce((a, b) => a + b, 0); let yy = y; doc.setFillColor(...C.navy); doc.rect(x, yy, total, rowH, 'F'); doc.setTextColor(...C.white); doc.setFont('helvetica', 'bold'); doc.setFontSize(6.8); let xx = x; headers.forEach((h, i) => { doc.text(h, xx + 4, yy + 11); xx += widths[i]; }); yy += rowH; rows.forEach((row, ri) => { doc.setFillColor(ri % 2 ? C.light[0] : C.white[0], ri % 2 ? C.light[1] : C.white[1], ri % 2 ? C.light[2] : C.white[2]); doc.setDrawColor(...C.border); doc.rect(x, yy, total, rowH, 'FD'); xx = x; doc.setTextColor(...C.text); doc.setFont('helvetica', 'normal'); doc.setFontSize(6.6); row.forEach((cell, i) => { doc.text(doc.splitTextToSize(String(cell), Math.max(24, widths[i] - 8)).slice(0, 2), xx + 4, yy + 11); xx += widths[i]; }); yy += rowH; }); return yy; }
async function png(svg: SVGSVGElement, w = 1100, h = 360) { const clone = svg.cloneNode(true) as SVGSVGElement; clone.setAttribute('width', String(w)); clone.setAttribute('height', String(h)); clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); const style = document.createElementNS('http://www.w3.org/2000/svg', 'style'); style.textContent = '.chart-grid{stroke:#dfe6ef}.chart-line.actual{fill:none;stroke:#2c67b4;stroke-width:3}.chart-line.forecast{fill:none;stroke:#ce8922;stroke-width:3;stroke-dasharray:7 5}.chart-line.upper{fill:none;stroke:#ce8922;stroke-dasharray:4 4}.forecast-band{fill:#ce8922;fill-opacity:.14}.threshold-line{stroke:#be4a41;stroke-dasharray:5 4}.chart-axis-label,.chart-axis-title,.threshold-label,.projection-label{font-family:Arial;font-size:11px;fill:#40566f}.projection-line{fill:none;stroke:#2c67b4;stroke-width:3}.projection-point{fill:#fff;stroke:#2c67b4;stroke-width:2}'; clone.insertBefore(style, clone.firstChild); return await new Promise<string>((resolve, reject) => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = w; canvas.height = h; const ctx = canvas.getContext('2d'); if (!ctx) return reject(new Error('canvas unavailable')); ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, w, h); ctx.drawImage(image, 0, 0, w, h); resolve(canvas.toDataURL('image/png')); }; image.onerror = () => reject(new Error('svg conversion failed')); image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(new XMLSerializer().serializeToString(clone))}`; }); }
async function addChart(doc: jsPDF, c: Chart, x: number, y: number, w: number, h: number) { doc.setTextColor(...C.navy); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text(c.title, x, y); doc.setTextColor(...C.muted); doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.text(`Unit: ${c.unit}`, x + w, y, { align: 'right' }); try { doc.addImage(await png(c.svg, 1100, Math.max(260, Math.round(h * 2.1))), 'PNG', x, y + 7, w, h - 7, undefined, 'FAST'); } catch { doc.text('Chart unavailable at capture time.', x, y + 23); } }
function simTableRows(s: Simulation | null) { if (!s) return []; const rows = [0, 30, 60, 90].map((day) => { const p = (name: string) => { const values = Object.entries(s.projections).find(([k]) => k.toLowerCase().includes(name))?.[1] || []; return values.find((x) => x.day === day)?.value ?? (day === 0 ? values[0]?.value : undefined); }; const traffic = s.currentTraffic + (s.targetTraffic - s.currentTraffic) * day / 90; return [`${day === 0 ? 'Now' : `${day} days`}`, `${traffic.toFixed(1)} req/min`, `${p('cpu')?.toFixed(1) ?? '—'}%`, `${p('memory')?.toFixed(1) ?? '—'}%`, `${p('disk')?.toFixed(1) ?? '—'}%`]; }); return rows; }
async function build(report: Report) { const doc = new jsPDF({ unit: 'pt', format: 'a4' }); const total = 9; let page = 1;
  header(doc, report, 'Capacity & Performance Report', 'Executive management view · live Dynatrace data'); let y = 110; doc.setTextColor(...C.navy); doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.text('Executive Summary', 38, y); y += 24; y = wrap(doc, `This report presents the live infrastructure capacity position for ${report.zone}, including host utilization, application throughput, Dynatrace Intelligence forecast context, AI-assisted assessment and the active traffic what-if scenario.`, 38, y, 515, 9, 13) + 12; const width = 250; report.kpis.slice(0, 6).forEach((k, i) => card(doc, 38 + (i % 2) * 264, y + Math.floor(i / 2) * 72, width, 62, k, i === 2 ? C.amber : i === 3 ? C.red : C.blue)); y += Math.ceil(Math.min(6, report.kpis.length) / 2) * 72 + 10; doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text('Key Findings', 38, y); y += 17; report.findings.slice(0, 6).forEach((f) => { y = wrap(doc, `• ${f}`, 46, y, 500, 8.5, 12) + 3; }); footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'AI Capacity Assessment', 'Dynatrace Assist assessment captured from the live application state.'); y = 110; const aiText = report.ai || 'Dynatrace Assist did not return an assessment during report generation.'; y = wrap(doc, aiText, 42, y, 500, 8.5, 12); footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Infrastructure Trend Analysis', 'Historical CPU, memory and disk utilization.'); y = 110; for (const key of ['CPU utilization', 'Memory utilization', 'Disk utilization']) { const c = report.charts.find((x) => x.title === key); if (c) { await addChart(doc, c, 42, y, 510, 145); y += 165; } } footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Application & Network Performance', 'Host-associated application throughput and network telemetry.'); y = 110; for (const c of report.charts.filter((x) => ['Application throughput', 'Network RX', 'Network TX'].includes(x.title))) { await addChart(doc, c, 42, y, 510, 145); y += 165; } footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Dynatrace Intelligence Forecast', 'Actual forecast rendered from the Capacity Forecast page.'); y = 110; if (report.forecastChart) { await addChart(doc, report.forecastChart, 42, y, 510, 300); y += 320; } else { y = wrap(doc, 'No rendered Dynatrace Intelligence forecast was available at report generation time. No forecast values have been fabricated.', 42, y, 510, 9, 13); } footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Host Resource Utilization', 'Current host-level estate view ordered by source table.'); y = 110; table(doc, 28, y, [190, 62, 88, 42, 48, 42, 56, 48], ['Host', 'Environment', 'Application', 'CPU', 'Memory', 'Disk', 'Throughput', 'Status'], report.hosts.slice(0, 32).map((h) => [h.host, h.environment, h.application, h.cpu, h.memory, h.disk, h.throughput, h.status]), 18); footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Traffic Simulation Trajectory', 'Current scenario traffic progression.'); y = 110; if (report.simulation) { const s = report.simulation; const rows = [[`Now`, `${s.currentTraffic.toFixed(1)}`], ['30 days', `${(s.currentTraffic + (s.targetTraffic - s.currentTraffic) / 3).toFixed(1)}`], ['60 days', `${(s.currentTraffic + 2 * (s.targetTraffic - s.currentTraffic) / 3).toFixed(1)}`], ['90 days', `${s.targetTraffic.toFixed(1)}`]]; y = table(doc, 70, y, [160, 180], ['Horizon', 'Application traffic'], rows, 24) + 25; doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text(`Scenario growth: ${s.growth.toFixed(1)}%`, 70, y); } else y = wrap(doc, 'No what-if scenario was rendered during report capture.', 42, y, 510, 9, 13); footer(doc, page++, total);
  doc.addPage(); header(doc, report, '30 / 60 / 90-Day Resource Capacity Outlook', 'Traffic-driven resource projections captured from the simulation page.'); y = 110; table(doc, 45, y, [92, 115, 85, 95, 85], ['Horizon', 'Traffic', 'CPU', 'Memory', 'Disk'], simTableRows(report.simulation), 24); y += 145; for (const [name, values] of Object.entries(report.simulation?.projections || {})) { const last = values.at(-1); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...C.navy); doc.text(name, 45, y); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...C.muted); doc.text(`90-day projection: ${last ? `${last.value.toFixed(1)}%` : '—'}`, 190, y); y += 18; } footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'What-If Capacity Comparison', 'Current versus 90-day scenario utilization.'); y = 110; const s = report.simulation; if (s) { const getLast = (key: string) => { const vals = Object.entries(s.projections).find(([n]) => n.toLowerCase().includes(key))?.[1] || []; return vals.find((p) => p.day === 90)?.value ?? vals.at(-1)?.value ?? 0; }; const current = { cpu: getLast('cpu'), memory: getLast('memory'), disk: getLast('disk') }; const projected = { cpu: getLast('cpu'), memory: getLast('memory'), disk: getLast('disk') }; const rows = [['CPU', `${current.cpu.toFixed(1)}%`, `${projected.cpu.toFixed(1)}%`, `${(projected.cpu-current.cpu).toFixed(1)} pp`], ['Memory', `${current.memory.toFixed(1)}%`, `${projected.memory.toFixed(1)}%`, `${(projected.memory-current.memory).toFixed(1)} pp`], ['Disk', `${current.disk.toFixed(1)}%`, `${projected.disk.toFixed(1)}%`, `${(projected.disk-current.disk).toFixed(1)} pp`]]; table(doc, 70, y, [130, 110, 130, 110], ['Metric', 'Current', '90-day scenario', 'Delta'], rows, 25); y += 135; y = wrap(doc, 'The What-If analysis is a planning sensitivity model. It is not a Dynatrace Intelligence forecast and should be read together with the live telemetry and forecast pages.', 70, y, 455, 8.5, 12); } else y = wrap(doc, 'No active What-If scenario was available.', 42, y, 510, 9, 13); footer(doc, page++, total);
  doc.addPage(); header(doc, report, 'Methodology & Data Provenance', 'How the report values should be interpreted.'); y = 110; const notes = ['Live host CPU, memory, disk, network and host-associated throughput are sourced from the Dynatrace AppEngine data provider.', 'Application-service throughput is independently verified through request-root spans where available.', 'Dynatrace Intelligence forecasts are shown only when a forecast result is rendered by the application.', 'What-If resource projections are simulation outputs based on the traffic scenario selected in the Capacity Simulation page.', 'AI findings are copied from Dynatrace Assist output captured at report generation time.', 'Unavailable datasets are identified explicitly rather than replaced with invented values.']; for (const n of notes) y = wrap(doc, `• ${n}`, 46, y, 500, 8.5, 13) + 3; footer(doc, page++, total);
  doc.save(`axis-capacity-report-${new Date().toISOString().slice(0,10)}.pdf`);
}

export function installProductionPdfV5() { const w = window as Window & { __axisPdfV5?: boolean }; if (w.__axisPdfV5) return; w.__axisPdfV5 = true; document.addEventListener('click', async (event) => { const target = event.target instanceof Element ? event.target.closest<HTMLButtonElement>('.pdf-report-button') : null; if (!target) return; event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); target.disabled = true; const old = target.innerText; target.innerText = 'Preparing production report…'; try { const report = await collect(); await build(report); } catch (error) { console.error('[Axis PDF V5]', error); alert(`Report generation failed: ${error instanceof Error ? error.message : String(error)}`); } finally { target.disabled = false; target.innerText = old; } }, true); }
