import { jsPDF } from 'jspdf';

type ChartSnap = { title: string; unit: string; svg: SVGSVGElement; context: 'chart' | 'forecast' | 'simulation' };
type HostRow = { name: string; environment: string; application: string; cpu: number; memory: number; disk: number; throughput: number; status: string };
type KpiRow = { label: string; value: string; detail: string };
type SimulationSnap = { growth: number; additionalHosts: number; horizon: number; currentTraffic: number; simulatedTraffic: number; risk: string; capacityGap: number; recommendedExpansion: number; cpu: number; memory: number; disk: number };
type Snap = { page: string; charts: ChartSnap[]; ai: string; cards: KpiRow[]; hosts: HostRow[]; simulation: SimulationSnap | null; forecastText: string[] };

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
async function waitFor(test: () => boolean, timeout = 30000) { const start = Date.now(); while (Date.now() - start < timeout) { if (test()) return true; await sleep(250); } return false; }
function txt(e: Element | null) { return e?.textContent?.replace(/\s+/g, ' ').trim() || ''; }
function nav(name: string) { const b = [...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find((x) => x.innerText.trim() === name); b?.click(); }
function page() { return document.querySelector('.nav-item.active')?.textContent?.trim() || ''; }
function num(s: string) { const m = String(s).replace(/,/g, '').match(/-?\d+(?:\.\d+)?/); return m ? Number(m[0]) : 0; }
function metric(panel: Element): [string, string] { const t = txt(panel.querySelector('h2,.chart-title-row strong')).toLowerCase(); if (t.includes('memory')) return ['Memory utilization', '%']; if (t.includes('disk')) return ['Disk utilization', '%']; if (t.includes('network rx') || t.includes('receive')) return ['Network RX', 'B/s']; if (t.includes('network tx') || t.includes('transmit')) return ['Network TX', 'B/s']; if (t.includes('throughput')) return ['Application throughput', 'req/min']; return ['CPU utilization', '%']; }
function charts(): ChartSnap[] { return [...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg,.forecast-band-wrap svg,.projection-svg')].map((svg) => { const panel = svg.closest('.forecast-panel,.chart-panel,.projection-card,.forecast-band-wrap') || svg.parentElement || svg; const [title, unit] = metric(panel); const context = svg.classList.contains('projection-svg') || panel.classList.contains('projection-card') ? 'simulation' : panel.closest('.forecast-panel') ? 'forecast' : 'chart'; return { title, unit, context, svg: svg.cloneNode(true) as SVGSVGElement }; }); }
function cards(): KpiRow[] { return [...document.querySelectorAll<HTMLElement>('.metric-card')].map((card) => ({ label: txt(card.querySelector('p')), value: txt(card.querySelector('strong')), detail: txt(card.querySelector('small')) })).filter((x) => x.label || x.value); }
function hostRows(): HostRow[] { return [...document.querySelectorAll<HTMLTableRowElement>('tbody tr')].map((tr) => { const c = [...tr.cells].map(txt); return { name: c[0] || '—', environment: c[1] || '—', application: c[2] || '—', cpu: num(c[3]), memory: num(c[4]), disk: num(c[5]), throughput: num(c[6]), status: c[7] || '—' }; }).filter((x) => x.name !== '—'); }
function aiText() { return txt(document.querySelector('.ai-panel .ai-summary pre,.ai-panel .ai-summary,.ai-summary pre,.ai-summary')); }
function forecastText() { return [...document.querySelectorAll<HTMLElement>('.forecast-panel,.forecast-source,.forecast-select-row')].map(txt).filter(Boolean).slice(0, 10); }
function simulationSnap(hosts: HostRow[]): SimulationSnap | null {
  const root = document.querySelector('.simulation-enhanced'); if (!root) return null;
  const ranges = [...root.querySelectorAll<HTMLInputElement>('input[type="range"]')];
  const growth = ranges[0] ? Number(ranges[0].value) || 0 : 20;
  const additionalHosts = ranges[1] ? Number(ranges[1].value) || 0 : 0;
  const cardsNow = cards();
  const currentTraffic = num(cardsNow.find((x) => /current traffic/i.test(x.label))?.value || '0');
  const simulatedTraffic = num(cardsNow.find((x) => /simulated traffic/i.test(x.label))?.value || '') || currentTraffic * (1 + growth / 100);
  const avg = (k: 'cpu'|'memory'|'disk') => hosts.length ? hosts.reduce((s, h) => s + h[k], 0) / hosts.length : 0;
  const horizonSelect = [...document.querySelectorAll<HTMLSelectElement>('select')].find((s) => /forecast/i.test(s.parentElement?.textContent || '') && /days/i.test(s.parentElement?.textContent || ''));
  const period = Number(horizonSelect?.value) || 30;
  const factor = 1 + (growth / 100) * (period / 30);
  const hostFactor = (extra: number, perHost: number) => 1 + extra * perHost / 100;
  const cpu = avg('cpu') * factor / hostFactor(additionalHosts, 25);
  const memory = avg('memory') * factor / hostFactor(additionalHosts, 25);
  const disk = avg('disk') * factor / hostFactor(additionalHosts, 20);
  const peak = Math.max(cpu, memory, disk);
  const requiredHosts = Math.max(0, Math.ceil((peak - 80) / 12));
  const fallbackRisk = peak >= 95 ? 'Critical' : peak >= 85 ? 'High' : peak >= 75 ? 'Medium' : 'Low';
  const resultText = txt(root.querySelector('.simulation-result'));
  const risk = resultText.match(/Critical|High|Medium|Low/i)?.[0] || fallbackRisk;
  return { growth, additionalHosts, horizon: period, currentTraffic, simulatedTraffic, risk, capacityGap: Math.max(0, peak - 80), recommendedExpansion: Math.max(0, requiredHosts - additionalHosts), cpu, memory, disk };
}
function snap(): Snap { const h = hostRows(); return { page: page(), charts: charts(), ai: aiText(), cards: cards(), hosts: h, simulation: simulationSnap(h), forecastText: forecastText() }; }
async function ensureForecast() { nav('Capacity Forecast'); await sleep(700); const run = [...document.querySelectorAll<HTMLButtonElement>('button')].find((b) => /Run \d+-day forecast/i.test(b.innerText)); const has = document.querySelector('.forecast-panel .chart-wrap svg'); if (!has && run) { run.click(); await waitFor(() => Boolean(document.querySelector('.forecast-panel .chart-wrap svg')), 30000); } await sleep(500); }
async function ensureAi() { nav('Overview'); await sleep(600); if (!aiText()) { const b = [...document.querySelectorAll<HTMLButtonElement>('.ai-panel button,.ai-button')].find((x) => /Generate AI Assessment/i.test(x.innerText)); if (b) { b.click(); await waitFor(() => Boolean(aiText()), 45000); } } }
async function collect(): Promise<Snap[]> {
  await ensureForecast();
  await ensureAi();
  const out: Snap[] = [snap()];
  nav('Host Inventory'); await sleep(900); const inv = snap();
  if (inv.hosts.length) { const row = document.querySelector<HTMLTableRowElement>('tbody tr'); row?.click(); await sleep(500); for (const key of ['throughput','cpu','memory','disk','networkRx','networkTx']) { const select = [...document.querySelectorAll<HTMLSelectElement>('.chart-panel select')][0]; if (select) { const opt = [...select.options].find((o) => o.value === key || o.text.toLowerCase().replace(/[^a-z]/g,'').includes(key.toLowerCase().replace(/[^a-z]/g,''))); if (opt) { select.value = opt.value; select.dispatchEvent(new Event('change', { bubbles: true })); await sleep(350); } } const s = snap(); s.hosts = inv.hosts; out.push(s); } } else out.push(inv);
  await ensureForecast(); out.push(snap());
  nav('Simulation'); await sleep(700); await waitFor(() => Boolean(document.querySelector('.simulation-enhanced')), 5000); out.push(snap());
  return out;
}
function svgPng(svg: SVGSVGElement, w = 1100, h = 420) { const s = svg.cloneNode(true) as SVGSVGElement; s.setAttribute('width', String(w)); s.setAttribute('height', String(h)); s.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); const style = document.createElementNS('http://www.w3.org/2000/svg','style'); style.textContent = '.chart-grid{stroke:#dfe6ef;stroke-width:1}.chart-line.actual{fill:none;stroke:#327fe6;stroke-width:3}.chart-line.forecast{fill:none;stroke:#e88b32;stroke-width:3;stroke-dasharray:7 5}.chart-line.upper{fill:none;stroke:#e88b32;stroke-width:1.5;stroke-dasharray:4 4}.forecast-band{fill:#e88b32;fill-opacity:.16}.threshold-line{stroke:#d55d4b;stroke-width:1.5;stroke-dasharray:5 4}.chart-axis-label,.chart-axis-title,.threshold-label,.projection-label{font-family:Arial,sans-serif;font-size:11px;fill:#40566f}.projection-line{fill:none;stroke:#327fe6;stroke-width:3}.projection-point{fill:#fff;stroke:#327fe6;stroke-width:2}.forecast-split{stroke:#9aaabd;stroke-width:1;stroke-dasharray:4 4}'; s.insertBefore(style,s.firstChild); return new Promise<string>((resolve,reject)=>{ const img=new Image(); img.onload=()=>{ const c=document.createElement('canvas'); c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)return reject(new Error('canvas'));ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/png'));};img.onerror=()=>reject(new Error('svg'));img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(s)); }); }
function wrap(doc: jsPDF, s: string, x: number, y: number, w: number, size=8.5, lead=12) { doc.setFontSize(size); const lines=doc.splitTextToSize(s,w); doc.text(lines,x,y); return y+lines.length*lead; }
function header(doc: jsPDF,title:string,sub:string){doc.setTextColor(20,35,56);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES',40,30);doc.setFontSize(18);doc.text(title,40,53);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(sub,40,66);doc.text(`Generated ${new Date().toLocaleString('en-IN')}`,40,78);doc.setDrawColor(215,222,232);doc.line(40,86,555,86);}
function footer(doc:jsPDF,n:number){doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(110,120,135);doc.text('Axis Davis Capacity Planner · Live Dynatrace telemetry · Planning report',40,815);doc.text(`Page ${n}`,520,815);}
async function addChart(doc:jsPDF,c:ChartSnap,x:number,y:number,w:number,h:number){doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(20,35,56);doc.text(c.title,x,y);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${c.unit}`,x+w-75,y);try{doc.addImage(await svgPng(c.svg,1100,Math.max(280,Math.round(h*2.2))),'PNG',x,y+8,w,h-10,undefined,'FAST');}catch{doc.setFontSize(8);doc.text('Chart could not be rendered from the captured application state.',x,y+28);}}
function table(doc:jsPDF,headers:string[],rows:string[][],x:number,y:number,widths:number[],rowH=18){const draw=(cells:string[],head:boolean)=>{let xx=x;doc.setFillColor(head?38:248,head?82:250,head?124:252);doc.setDrawColor(215,222,232);doc.setFont('helvetica',head?'bold':'normal');doc.setFontSize(head?7:6.8);doc.setTextColor(head?255:35,head?255:45,head?255:60);cells.forEach((cell,i)=>{doc.rect(xx,y,widths[i],rowH,'FD');const lines=doc.splitTextToSize(cell||'—',widths[i]-7).slice(0,2);doc.text(lines,xx+3,y+11);xx+=widths[i];});y+=rowH;};draw(headers,true);for(const r of rows){if(y>770)break;draw(r,false);}return y;}
function kpiRows(rows:KpiRow[]){return rows.map((r)=>[r.label,r.value,r.detail]);}
function metricValues(hosts:HostRow[]){const avg=(k:'cpu'|'memory'|'disk')=>hosts.length?hosts.reduce((s,h)=>s+h[k],0)/hosts.length:0;return {cpu:avg('cpu'),memory:avg('memory'),disk:avg('disk')};}
function trajectory(sim:SimulationSnap,current:number){return [0,30,60,90].map((d)=>({day:d,traffic:current*(1+(sim.growth/100)*(d/30))}));}
function findings(ai:string,sim:SimulationSnap|null,fc:Snap|undefined,hosts:HostRow[]){const lines:string[]=[];if(ai){const section=ai.match(/Key Findings([\s\S]*?)(?:Capacity Risks|Recommended Actions|30\/60\/90-day planning recommendation|$)/i)?.[1];if(section)lines.push(...section.split(/\n+/).map((x)=>x.replace(/^[-•*]\s*/,'').trim()).filter(Boolean).slice(0,6));}const vals=metricValues(hosts);const maxMetric=Object.entries(vals).sort((a,b)=>b[1]-a[1])[0];if(maxMetric)lines.push(`${maxMetric[0].replace('cpu','CPU').replace('memory','Memory').replace('disk','Disk')} is the highest current average resource utilization at ${maxMetric[1].toFixed(1)}%.`);if(sim)lines.push(`At the selected +${sim.growth}% traffic scenario over ${sim.horizon}-day planning horizon, projected CPU ${sim.cpu.toFixed(1)}%, memory ${sim.memory.toFixed(1)}%, and disk ${sim.disk.toFixed(1)}% with ${sim.risk} risk.`);if(fc?.charts.some(c=>c.context==='forecast'))lines.push('Dynatrace Intelligence forecast is included with historical and forecast segments.');return [...new Set(lines)].slice(0,8);}
function recommendations(ai:string,sim:SimulationSnap|null){if(ai){const m=ai.match(/Recommended Actions([\s\S]*?)(?:30\/60\/90-day planning recommendation|$)/i);if(m){const rows=m[1].split(/\n+/).map(x=>x.replace(/^[-•*#]+\s*/,'').trim()).filter(Boolean);if(rows.length)return rows.slice(0,12);}}const r:string[]=[];if(sim){if(sim.risk==='Critical'||sim.risk==='High')r.push('Prioritize capacity remediation before the selected planning horizon.');else if(sim.risk==='Medium')r.push('Monitor resource trajectory and review capacity headroom before the horizon.');else r.push('Current what-if resource projections remain below the planning risk threshold. Continue trend monitoring.');r.push(`Review disk projection (${sim.disk.toFixed(1)}%) and memory projection (${sim.memory.toFixed(1)}%) at the selected traffic scenario.`);}r.push('Re-run Dynatrace Intelligence after material workload or infrastructure changes.');return r;}
function addTextBlock(doc:jsPDF,title:string,text:string,x:number,y:number,w:number){doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(20,35,56);doc.text(title,x,y);return wrap(doc,text,x,y+16,w,8.2,11)+6;}
async function build(snaps:Snap[]){const doc=new jsPDF({unit:'pt',format:'a4'});let pno=1;const overview=snaps.find(x=>x.page.includes('Overview'))||snaps[0];const inv=snaps.find(x=>x.page.includes('Host Inventory'));const fc=[...snaps].reverse().find(x=>x.page.includes('Capacity Forecast'));const sim=snaps.find(x=>x.page.includes('Simulation'))?.simulation||null;const hosts=inv?.hosts||overview?.hosts||[];const infra=(key:string)=>[...snaps].reverse().find(x=>x.charts.some(c=>c.title.toLowerCase().includes(key)))?.charts.find(c=>c.title.toLowerCase().includes(key));
header(doc,'Capacity & Performance Report',`${overview?.cards.find(x=>/Total Hosts/i.test(x.label))?.value||hosts.length} hosts · Live Dynatrace · Capacity planning`);let y=112;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Executive Summary',40,y);y+=22;y=wrap(doc,'This report combines live Dynatrace host telemetry, independently verified application-service throughput, Dynatrace Intelligence forecasting and the selected traffic what-if scenario. Values are captured from the application at report-generation time.',40,y,515,9,13)+10;y=table(doc,['Metric','Current value','Context'],kpiRows(overview?.cards||[]),40,y,[160,125,230],22)+14;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Key Findings',40,y);y+=18;for(const f of findings(overview?.ai||'',sim,fc,hosts))y=wrap(doc,`• ${f}`,48,y,500,8.5,12)+3;if(overview?.ai)y=addTextBlock(doc,'AI Executive Assessment',overview.ai.slice(0,1800),40,y+8,515);footer(doc,pno++);

doc.addPage();header(doc,'AI Capacity Assessment & Recommendations','Dynatrace Intelligence / Dynatrace Assist output captured from the live application.');y=110;if(overview?.ai){y=addTextBlock(doc,'AI-assisted capacity assessment',overview.ai,40,y,515);}else{y=wrap(doc,'AI assessment was not returned during capture. Generate the AI assessment on the Overview page before exporting if Assist is temporarily unavailable.',40,y,515,9,13);}y+=10;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Prioritized Recommendations',40,y);y+=18;for(const r of recommendations(overview?.ai||'',sim))y=wrap(doc,`• ${r}`,48,y,500,8.5,12)+4;footer(doc,pno++);

doc.addPage();header(doc,'Infrastructure Trend Analysis','Live host telemetry for CPU, memory and disk utilization.');y=110;for(const key of ['cpu','memory','disk']){const c=infra(key);if(c){await addChart(doc,c,48,y,500,155);y+=175;}}footer(doc,pno++);

doc.addPage();header(doc,'Application Throughput & Network Telemetry','Application-service throughput and host network activity.');y=110;for(const key of ['throughput','network rx','network tx']){const c=infra(key);if(c){await addChart(doc,c,48,y,500,155);y+=175;}}footer(doc,pno++);

doc.addPage();header(doc,'Dynatrace Intelligence Forecast','Actual Dynatrace Intelligence forecast with historical telemetry and prediction interval.');y=110;const fcChart=fc?.charts.find(c=>c.context==='forecast')||fc?.charts.find(c=>c.title.toLowerCase().includes('utilization'));if(fcChart){await addChart(doc,fcChart,48,y,500,315);y+=335;for(const t of fc?.forecastText||[])y=wrap(doc,t,48,y,500,8,11)+2;}else{y=wrap(doc,'No forecast chart was captured. The exporter attempted to run the selected Dynatrace Intelligence forecast before capture; no synthetic forecast values are inserted.',48,y,500,9,13);}footer(doc,pno++);

doc.addPage();header(doc,'Host Resource Utilization','Current host-level CPU, memory, disk and application throughput.');y=108;const sorted=[...hosts].sort((a,b)=>Math.max(b.cpu,b.memory,b.disk)-Math.max(a.cpu,a.memory,a.disk));y=table(doc,['Host','Environment','CPU','Memory','Disk','App throughput','Status'],sorted.slice(0,45).map(h=>[h.name,h.environment,`${h.cpu.toFixed(1)}%`,`${h.memory.toFixed(1)}%`,`${h.disk.toFixed(1)}%`,`${h.throughput.toFixed(1)} req/min`,h.status]),32,y,[185,65,45,50,45,75,55],18);y+=12;doc.setFontSize(7.5);doc.setFont('helvetica','italic');doc.text(`Showing ${Math.min(45,sorted.length)} of ${sorted.length} hosts.`,32,y);footer(doc,pno++);

doc.addPage();header(doc,'Traffic Simulation Trajectory','Throughput trajectory using the same planning-growth model as the application capacity simulation.');y=110;if(sim){const t=trajectory(sim,sim.currentTraffic);const rows=t.map(x=>[`${x.day} days`,`${x.traffic.toFixed(1)} req/min`,x.day===0?'Baseline':`+${Math.round((x.traffic/sim.currentTraffic-1)*100)}%`]);y=table(doc,['Horizon','Scenario throughput','Change vs baseline'],rows,48,y,[110,180,170],20)+18;const vals=t.map(x=>x.traffic);const maxTraffic=Math.max(...vals,1), minTraffic=Math.min(...vals,0), span=Math.max(1,maxTraffic-minTraffic);const pts=t.map((x,i)=>`${55+i*505/(t.length-1)},${205-((x.traffic-minTraffic)/span)*165}`).join(' ');const fake:ChartSnap={title:'Throughput simulation trajectory',unit:'req/min',context:'simulation',svg:(()=>{const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 600 260');s.innerHTML=`<line x1="55" y1="205" x2="560" y2="205" class="chart-grid"/><line x1="55" y1="40" x2="55" y2="205" class="chart-grid"/><polyline class="projection-line" points="${pts}"/>${t.map((x,i)=>`<circle class="projection-point" cx="${55+i*505/(t.length-1)}" cy="${205-((x.traffic-minTraffic)/span)*165}" r="4"/><text x="${45+i*505/(t.length-1)}" y="230" class="chart-axis-label">${x.day===0?'Now':x.day+'d'}</text>`).join('')}<text x="55" y="25" class="chart-axis-title">req/min</text>`;return s;})()};await addChart(doc,fake,48,y,500,190);y+=205;doc.setFontSize(8);doc.text(`Baseline ${sim.currentTraffic.toFixed(1)} req/min · selected traffic growth +${sim.growth}% · ${sim.additionalHosts} additional hosts`,48,y);}else{y=wrap(doc,'No simulation state was available during capture.',48,y,500,9,13);}footer(doc,pno++);

doc.addPage();header(doc,'30 / 60 / 90-Day Resource Capacity Outlook','CPU, memory and disk projections using the exact capacity-simulation formula used by the application.');y=108;if(sim){const base=metricValues(hosts);const checkpoints=[30,60,90].map(d=>{const factor=1+(sim.growth/100)*(d/30);const extra=(k:number)=>1+sim.additionalHosts*k/100;return [String(d),`${(sim.currentTraffic*factor).toFixed(1)} req/min`,`${(base.cpu*factor/extra(25)).toFixed(1)}%`,`${(base.memory*factor/extra(25)).toFixed(1)}%`,`${(base.disk*factor/extra(20)).toFixed(1)}%`];});y=table(doc,['Horizon','Scenario throughput','CPU utilization','Memory utilization','Disk utilization'],checkpoints,36,y,[72,112,100,110,100],22)+18;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Selected-horizon capacity result',36,y);y+=17;for(const line of [`Planning horizon: ${sim.horizon} days`,`Traffic growth: +${sim.growth}%`,`Additional hosts: ${sim.additionalHosts}`,`Projected CPU: ${sim.cpu.toFixed(1)}%`,`Projected Memory: ${sim.memory.toFixed(1)}%`,`Projected Disk: ${sim.disk.toFixed(1)}%`,`Risk: ${sim.risk}`,`Capacity gap above 80% threshold: ${sim.capacityGap.toFixed(1)} percentage points`,`Recommended expansion: ${sim.recommendedExpansion} host(s)`]){y=wrap(doc,`• ${line}`,44,y,500,8.5,12)+2;}}footer(doc,pno++);

doc.addPage();header(doc,'What-If Capacity Simulation','Current versus selected-horizon resource utilization and scenario deltas.');y=108;if(sim){const base=metricValues(hosts);y=table(doc,['Metric','Current','Projected','Delta'],[['CPU',`${base.cpu.toFixed(1)}%`,`${sim.cpu.toFixed(1)}%`,`${(sim.cpu-base.cpu).toFixed(1)} pp`],['Memory',`${base.memory.toFixed(1)}%`,`${sim.memory.toFixed(1)}%`,`${(sim.memory-base.memory).toFixed(1)} pp`],['Disk',`${base.disk.toFixed(1)}%`,`${sim.disk.toFixed(1)}%`,`${(sim.disk-base.disk).toFixed(1)} pp`]],48,y,[150,105,125,105],24)+20;y=wrap(doc,`This scenario models the effect of a +${sim.growth}% traffic change over the selected ${sim.horizon}-day planning horizon. The CPU / memory / disk projections use the same growth and additional-host factors as the application's runCapacitySimulation service.`,48,y,500,8.5,12)+15;doc.setFont('helvetica','bold');doc.text('Simulation trajectory',48,y);y+=15;const t=trajectory(sim,sim.currentTraffic);y=table(doc,['Day','Traffic','CPU','Memory','Disk'],t.map(x=>{const factor=x.traffic/sim.currentTraffic;return [`${x.day}`,`${x.traffic.toFixed(1)} req/min`,`${(base.cpu*factor).toFixed(1)}%`,`${(base.memory*factor).toFixed(1)}%`,`${(base.disk*factor).toFixed(1)}%`]}),48,y,[70,120,90,100,90],20);}footer(doc,pno++);

doc.addPage();header(doc,'Capacity Planning Conclusions','Decision-ready summary for SRE and infrastructure planning.');y=110;for(const f of findings(overview?.ai||'',sim,fc,hosts))y=wrap(doc,`• ${f}`,48,y,500,9,13)+4;y+=10;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Recommended Actions',48,y);y+=18;for(const r of recommendations(overview?.ai||'',sim))y=wrap(doc,`• ${r}`,48,y,500,8.5,12)+3;y+=10;doc.setFont('helvetica','bold');doc.text('Data provenance',48,y);y+=18;y=wrap(doc,'Live telemetry: Dynatrace DQL. Application throughput: independently verified request-root spans. Forecast: Dynatrace Intelligence Generic Forecast Analyzer. Simulation: application runCapacitySimulation formula. AI: Dynatrace Assist response captured from the Overview page.',48,y,500,8,11);footer(doc,pno++);

doc.save('axis-capacity-report.pdf');}
export function installProductionPdfV4(){const w=window as Window & {__axisPdfV6?:boolean};if(w.__axisPdfV6)return;w.__axisPdfV6=true;document.addEventListener('click',async(e)=>{const b=e.target instanceof Element?e.target.closest('.pdf-report-button'):null;if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();b.setAttribute('disabled','true');try{await build(await collect());}catch(err){console.error('PDF V6',err);alert(`PDF generation failed: ${err instanceof Error?err.message:String(err)}`);}finally{b.removeAttribute('disabled');}},true);}
