import { jsPDF } from 'jspdf';
import type { ForecastHorizon, Host, TimeRange } from '@/types';
import { dynatraceDataProvider } from './realDynatrace';
import { generateAssistCapacitySummary, getDynatraceForecasts, type DynatraceForecast } from './dynatraceIntelligence';
import { runCapacitySimulation } from './services/capacitySimulation';

type QaState={question:string;answer:string};
type ResourcePoint={day:number;traffic:number;cpu:number;memory:number;disk:number};
const C={navy:[22,41,67] as const,blue:[44,103,180] as const,amber:[206,137,34] as const,green:[45,132,91] as const,text:[37,49,66] as const,muted:[95,109,128] as const,border:[214,222,232] as const,light:[247,249,252] as const,white:[255,255,255] as const};
const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
const text=(e:Element|null|undefined)=>e?.textContent?.replace(/\s+/g,' ').trim()||'';
const number=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:Number(String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/)?.[0]||0);
const scope=()=>{
  const selects=[...document.querySelectorAll<HTMLSelectElement>('.top-actions select')];
  return {
    zone:selects.find(s=>[...s.options].some(o=>o.textContent?.trim()==='All Management Zones'))?.value||'All Management Zones',
    range:(selects.find(s=>['1h','6h','24h','7d','30d'].includes(s.value))?.value||'24h') as TimeRange,
    horizon:(Number(selects.find(s=>['7','14','30','60','90'].includes(s.value))?.value||30)) as ForecastHorizon,
  };
};
const scenario=()=>{
  const sliders=[...document.querySelectorAll<HTMLInputElement>('.simulation-controls input[type="range"]')];
  const growth=Number(sliders[0]?.value??0);const additionalHosts=Number(sliders[1]?.value??0);
  return {growth:Number.isFinite(growth)?growth:0,additionalHosts:Number.isFinite(additionalHosts)?additionalHosts:0};
};
const lastQa=():QaState=>((window as Window & {__axisDavisLastQa?:QaState}).__axisDavisLastQa)||{question:'',answer:''};
async function liveHosts(zone:string,range:TimeRange){return dynatraceDataProvider.getHosts(zone,range);}
async function pollDql<T>(query:string):Promise<T[]>{
  const {queryExecutionClient}=await import('@dynatrace-sdk/client-query');
  const response=await queryExecutionClient.queryExecute({body:{query,requestTimeoutMilliseconds:30000,maxResultRecords:500}});
  let result=response.result as {records?:Array<T|null>}|undefined;let token=response.requestToken;let state=response.state;
  for(let i=0;!result&&token&&i<30;i+=1){const p=await queryExecutionClient.queryPoll({requestToken:token,requestTimeoutMilliseconds:30000});state=p.state;result=p.result as {records?:Array<T|null>}|undefined;if(!result&&state==='RUNNING')await sleep(300);}
  if(!result)throw new Error(`DQL did not complete (state: ${state}).`);
  return(result.records??[]).filter(Boolean) as T[];
}
function avg(hosts:Host[],key:'cpu'|'memory'|'disk'){return hosts.length?hosts.reduce((s,h)=>s+number(h.telemetry.at(-1)?.[key]),0)/hosts.length:0;}
function throughput(hosts:Host[]){return hosts.reduce((s,h)=>s+number(h.telemetry.at(-1)?.throughput),0);}
function header(doc:jsPDF,title:string,sub:string,generated:string){doc.setFillColor(...C.navy);doc.rect(0,0,595,82,'F');doc.setTextColor(...C.white);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES',38,25);doc.setFontSize(19);doc.text(title,38,49);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(sub,38,66);doc.text(generated,557,25,{align:'right'});}
function footer(doc:jsPDF,page:number,total:number){doc.setDrawColor(...C.border);doc.line(38,790,557,790);doc.setTextColor(...C.muted);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text('Axis Davis Capacity Planner · Live Dynatrace telemetry · Management planning report',38,805);doc.text(`${page} / ${total}`,557,805,{align:'right'});}
function wrap(doc:jsPDF,s:string,x:number,y:number,w:number,size=8.5,lead=12){doc.setFontSize(size);const lines=doc.splitTextToSize(s,w);doc.text(lines,x,y);return y+lines.length*lead;}
function drawTable(doc:jsPDF,x:number,y:number,widths:number[],headers:string[],rows:string[][],rowH=19){const total=widths.reduce((a,b)=>a+b,0);let yy=y;doc.setFillColor(...C.navy);doc.rect(x,yy,total,rowH,'F');doc.setTextColor(...C.white);doc.setFont('helvetica','bold');doc.setFontSize(7);let xx=x;headers.forEach((h,i)=>{doc.text(h,xx+4,yy+12);xx+=widths[i];});yy+=rowH;rows.forEach((row,ri)=>{doc.setFillColor(...(ri%2?C.light:C.white));doc.setDrawColor(...C.border);doc.rect(x,yy,total,rowH,'FD');doc.setTextColor(...C.text);doc.setFont('helvetica','normal');doc.setFontSize(6.7);xx=x;row.forEach((cell,i)=>{doc.text(doc.splitTextToSize(String(cell),Math.max(20,widths[i]-8)).slice(0,2),xx+4,yy+11);xx+=widths[i];});yy+=rowH;});return yy;}
function drawLineChart(doc:jsPDF,x:number,y:number,w:number,h:number,points:Array<{x:number;y:number;label:string}>[],title:string,unit:string,dash=false){doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text(title,x,y);doc.setTextColor(...C.muted);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${unit}`,x+w,y,{align:'right'});const left=x+42,right=x+w-12,top=y+20,bottom=y+h-28;const max=Math.max(1,...points.map(p=>p.y));const min=Math.min(0,...points.map(p=>p.y));for(let i=0;i<=4;i++){const gy=top+(bottom-top)*i/4;doc.setDrawColor(...C.border);doc.line(left,gy,right,gy);doc.setTextColor(...C.muted);doc.setFontSize(6.5);doc.text((max-(max-min)*i/4).toFixed(1),x,gy+2);}if(points.length<2)return;const xy=points.map((p,i)=>({x:left+(right-left)*i/(points.length-1),y:bottom-(p.y-min)/Math.max(1,max-min)*(bottom-top)}));doc.setDrawColor(...C.blue);doc.setLineWidth(2);if(dash)doc.setLineDashPattern([7,5],0);for(let i=1;i<xy.length;i++)doc.line(xy[i-1].x,xy[i-1].y,xy[i].x,xy[i].y);doc.setLineDashPattern([],0);doc.setLineWidth(.2);xy.forEach((p,i)=>{doc.setFillColor(...C.white);doc.setDrawColor(...C.blue);doc.circle(p.x,p.y,3,'FD');doc.setTextColor(...C.text);doc.setFontSize(6.5);doc.text(points[i].label,p.x-12,bottom+12);doc.text(points[i].y.toFixed(1),p.x-10,p.y-8);});}
function aiSections(ai:string){return ai.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(s=>s.replace(/^#+\s*/,'').replace(/^[-•]\s*/,''));}
async function buildReport(){
  const {zone,range,horizon}=scope();const sc=scenario();const hosts=await liveHosts(zone,range);const cpu=avg(hosts,'cpu'),memory=avg(hosts,'memory'),disk=avg(hosts,'disk'),currentTraffic=Math.max(1,throughput(hosts));
  const resource:ResourcePoint[]=[0,30,60,90].map(day=>{if(day===0)return{day,traffic:currentTraffic,cpu,memory,disk};const r=runCapacitySimulation({cpuCapacity:Math.max(1,cpu),memoryCapacity:Math.max(1,memory),diskCapacity:Math.max(1,disk),trafficGrowth:sc.growth,transactionGrowth:sc.growth,period:day as ForecastHorizon,additionalHosts:sc.additionalHosts,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});return{day,traffic:currentTraffic*Math.pow(1+sc.growth/100,day/90),cpu:r.projectedCpu,memory:r.projectedMemory,disk:r.projectedDisk};});
  let forecast:DynatraceForecast|null=null;try{const results=await getDynatraceForecasts(hosts,'cpu',horizon);forecast=results.find(x=>x.forecast.forecast.length>0)?.forecast||null;}catch{}
  let ai='';let aiSource='Unavailable';try{const result=await generateAssistCapacitySummary(hosts,zone,forecast?([{host:hosts[0],forecast}]):[]);ai=result.text;aiSource=result.source;}catch(error){ai=`Capacity assessment unavailable. ${error instanceof Error?error.message:String(error)}`;}
  let problemCount='Unavailable';try{const rows=await pollDql<{count?:unknown}>(`fetch dt.davis.problems, from:now()-30d, to:now() | filter isNotNull(dt.entity.host) | summarize problems=countDistinct(event.id)`);problemCount=String(rows[0]?.count??rows[0]?.problems??'Unavailable');}catch{}
  const generated=new Date().toLocaleString('en-IN');const qa=lastQa();const total=8;const doc=new jsPDF({unit:'pt',format:'a4'});let p=1;
  header(doc,'Capacity & Performance Report','Executive management view · live Dynatrace data',generated);let y=108;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Executive Summary',38,y);y+=22;y=wrap(doc,`Management Zone: ${zone}. Current data: ${range}. Forecast horizon: ${horizon} days. Active simulation: +${sc.growth}% traffic growth with ${sc.additionalHosts} additional host(s).`,38,y,515,8.7,12)+12;drawTable(doc,38,y,[120,120,120,120],['Metric','Current','90-day','Status'],[['Hosts',String(hosts.length),'—','Live'],['CPU',`${cpu.toFixed(1)}%`,`${resource.at(-1)!.cpu.toFixed(1)}%`,'Capacity'],['Memory',`${memory.toFixed(1)}%`,`${resource.at(-1)!.memory.toFixed(1)}%`,'Capacity'],['Disk',`${disk.toFixed(1)}%`,`${resource.at(-1)!.disk.toFixed(1)}%`,'Capacity']]);y+=105;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(...C.navy);doc.text('Key Findings',38,y);y+=16;for(const line of [`${hosts.length} host(s) are included in the selected scope. Average CPU ${cpu.toFixed(1)}%, memory ${memory.toFixed(1)}%, disk ${disk.toFixed(1)}%.`,`Traffic progresses from ${currentTraffic.toFixed(1)} req/min now to ${resource.at(-1)!.traffic.toFixed(1)} req/min at 90 days.`,`Dynatrace Intelligence forecast: ${forecast?.forecast.length?'available':'unavailable'} for the selected CPU scope.`,`Distinct Davis problems in the last 30 days: ${problemCount}.`]){y=wrap(doc,`• ${line}`,46,y,505,8.5,12)+3;}footer(doc,p++,total);
  doc.addPage();header(doc,'AI Capacity Assessment',`Dynatrace Assist source: ${aiSource}`,generated);y=108;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Capacity Planning Assessment',38,y);y+=22;for(const line of aiSections(ai)){y=wrap(doc,line,42,y,500,8.4,12)+9;if(y>735)break;}footer(doc,p++,total);
  doc.addPage();header(doc,'Infrastructure Trend Analysis','CPU, memory and disk from live Axis host telemetry',generated);drawLineChart(doc,42,110,510,180,resource.map(r=>({x:r.day,y:r.cpu,label:r.day===0?'Now':`${r.day}d`})),'CPU utilization','%');drawLineChart(doc,42,305,510,180,resource.map(r=>({x:r.day,y:r.memory,label:r.day===0?'Now':`${r.day}d`})),'Memory utilization','%');drawLineChart(doc,42,500,510,180,resource.map(r=>({x:r.day,y:r.disk,label:r.day===0?'Now':`${r.day}d`})),'Disk utilization','%');footer(doc,p++,total);
  doc.addPage();header(doc,'Application & Network Performance','Current live application throughput for the selected scope',generated);drawLineChart(doc,42,110,510,260,resource.map(r=>({x:r.day,y:r.traffic,label:r.day===0?'Now':`${r.day}d`})),'Traffic trajectory','req/min');y=410;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Current host throughput sample',42,y);y+=18;const topHosts=hosts.slice().sort((a,b)=>number(b.telemetry.at(-1)?.throughput)-number(a.telemetry.at(-1)?.throughput)).slice(0,12);drawTable(doc,42,y,[230,90,90,100],['Host','CPU','Memory','Throughput'],topHosts.map(h=>{const q=h.telemetry.at(-1);return[h.name,`${number(q?.cpu).toFixed(1)}%`,`${number(q?.memory).toFixed(1)}%`,`${number(q?.throughput).toFixed(0)} req/min`]}),18);footer(doc,p++,total);
  doc.addPage();header(doc,'Dynatrace Intelligence Forecast',`CPU · ${horizon} days · selected Axis Bank scope`,generated);if(forecast?.forecast.length){drawLineChart(doc,42,110,510,330,forecast.forecast.map((v,i)=>({x:i,y:v,label:i===0?'Now':`${i+1}d`})),'CPU forecast','%',true);y=475;drawTable(doc,42,y,[170,170,170],['Forecast detail','Value','Status'],[['Source',forecast.source,forecast.status],['Quality',forecast.quality,'Valid'],['Forecast end',forecast.forecastEnd?new Date(forecast.forecastEnd).toLocaleString('en-IN'):'—','Available']]);}else{doc.setTextColor(...C.muted);doc.setFontSize(10);doc.text('No forecast values were returned during report generation.',42,130);}footer(doc,p++,total);
  doc.addPage();header(doc,'Host Resource Utilization','Current host inventory for the selected scope',generated);drawTable(doc,38,108,[185,92,58,62,58,75],['Host','Application','CPU','Memory','Disk','Throughput'],hosts.map(h=>{const q=h.telemetry.at(-1);return[h.name,h.application,`${number(q?.cpu).toFixed(1)}%`,`${number(q?.memory).toFixed(1)}%`,`${number(q?.disk).toFixed(1)}%`,`${number(q?.throughput).toFixed(0)} req/min`]}),18);footer(doc,p++,total);
  doc.addPage();header(doc,'Traffic Simulation & Capacity Outlook',`Exact active scenario: +${sc.growth}% traffic growth · ${sc.additionalHosts} additional host(s)`,generated);drawLineChart(doc,42,110,510,200,resource.map(r=>({x:r.day,y:r.traffic,label:r.day===0?'Now':`${r.day}d`})),'Traffic Simulation Trajectory','req/min');y=340;drawTable(doc,42,y,[75,105,90,100,90],['Horizon','Traffic','CPU','Memory','Disk'],resource.map(r=>[r.day===0?'Now':`${r.day} days`,`${r.traffic.toFixed(1)} req/min`,`${r.cpu.toFixed(1)}%`,`${r.memory.toFixed(1)}%`,`${r.disk.toFixed(1)}%`]),19);const sim=runCapacitySimulation({cpuCapacity:Math.max(1,cpu),memoryCapacity:Math.max(1,memory),diskCapacity:Math.max(1,disk),trafficGrowth:sc.growth,transactionGrowth:sc.growth,period:90,additionalHosts:sc.additionalHosts,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});y+=115;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('What-If Capacity Comparison',42,y);y+=16;drawTable(doc,42,y,[145,115,115,115],['Metric','Current','90-day scenario','Delta'],[['CPU',`${cpu.toFixed(1)}%`,`${sim.projectedCpu.toFixed(1)}%`,`${(sim.projectedCpu-cpu).toFixed(1)} pp`],['Memory',`${memory.toFixed(1)}%`,`${sim.projectedMemory.toFixed(1)}%`,`${(sim.projectedMemory-memory).toFixed(1)} pp`],['Disk',`${disk.toFixed(1)}%`,`${sim.projectedDisk.toFixed(1)}%`,`${(sim.projectedDisk-disk).toFixed(1)} pp`]],19);footer(doc,p++,total);
  doc.addPage();header(doc,'Interactive Davis Capacity Copilot','Interactive capacity planning using live Axis Bank context',generated);y=108;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Ask Davis about capacity',38,y);y+=22;doc.setTextColor(...C.text);doc.setFont('helvetica','normal');doc.setFontSize(8.7);y=wrap(doc,'The Overview page supports interactive capacity questions. Davis can use live host telemetry, forecast context, read-only DQL/Grail evidence and what-if simulation to answer questions rather than relying only on a static summary.',38,y,515,8.7,12)+15;doc.setFillColor(...C.light);doc.setDrawColor(...C.border);doc.roundedRect(38,y,515,120,8,8,'FD');doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Example questions',52,y+18);doc.setTextColor(...C.text);doc.setFont('helvetica','normal');doc.setFontSize(8.2);['Which hosts are closest to CPU capacity?','What happens if traffic increases by 48%?','How many infrastructure problems were generated in the last 30 days?','What is the current memory trend for this Management Zone?','Which resource is the primary capacity constraint?'].forEach((q,i)=>doc.text(`• ${q}`,52,y+38+i*14));y+=145;doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Interactive session captured in this report',38,y);y+=18;if(qa.question){doc.setTextColor(...C.blue);doc.setFont('helvetica','bold');doc.setFontSize(9);y=wrap(doc,`Question: ${qa.question}`,48,y,500,9,12)+12;doc.setTextColor(...C.text);doc.setFont('helvetica','normal');doc.setFontSize(8);y=wrap(doc,`Davis answer: ${qa.answer||'Answer not captured.'}`,48,y,500,8,11)+12;}else{doc.setTextColor(...C.muted);doc.setFontSize(8);y=wrap(doc,'No interactive question was answered before PDF generation. Ask Davis a question first, then generate the PDF.',48,y,500,8,11)+12;}doc.setTextColor(...C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Agent context available',38,y);y+=18;doc.setTextColor(...C.text);doc.setFont('helvetica','normal');doc.setFontSize(8.2);['Selected Management Zone and live host inventory','CPU / memory / disk / network / throughput telemetry','Dynatrace Intelligence forecast context when requested','Read-only DQL/Grail evidence for arbitrary capacity questions','Traffic what-if simulation values and projected capacity impact'].forEach((q,i)=>doc.text(`• ${q}`,48,y+i*14));footer(doc,p++,total);
  for(let i=1;i<=total;i++){doc.setPage(i);footer(doc,i,total);}doc.save('axis-capacity-report.pdf');
}
export function installProductionPdfV5(){const w=window as Window & {__axisPdfV51?:boolean};if(w.__axisPdfV51)return;w.__axisPdfV51=true;document.addEventListener('click',async event=>{const button=event.target instanceof Element?event.target.closest('.pdf-report-button'):null;if(!button)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();(button as HTMLButtonElement).disabled=true;try{await buildReport();}catch(error){console.error('Axis PDF generation',error);alert(`PDF generation failed: ${error instanceof Error?error.message:String(error)}`);}finally{(button as HTMLButtonElement).disabled=false;}},true);}
