import { jsPDF } from 'jspdf';
import type { ForecastHorizon, Host, MetricKey, TimeRange } from '@/types';
import { dynatraceDataProvider } from './realDynatrace';
import { generateAssistCapacitySummary, getDynatraceForecasts, type DynatraceForecast } from './dynatraceIntelligence';
import { runCapacitySimulation } from './services/capacitySimulation';

type Point = { day: number; value: number };
type Kpi = { label: string; value: string; detail: string };
type Chart = { title: string; unit: string; svg: SVGSVGElement; context: 'history' | 'forecast' };
type HostRow = { host: string; environment: string; application: string; cpu: string; memory: string; disk: string; throughput: string; status: string };
type ReportData = { generated: string; zone: string; range: string; horizon: ForecastHorizon; kpis: Kpi[]; findings: string[]; aiText: string; aiSource: string; charts: Chart[]; forecast: DynatraceForecast | null; forecastHost: string; hosts: HostRow[]; currentTraffic: number; trafficGrowth: number; additionalHosts: number; trafficTrajectory: Point[]; resourceTrajectory: { day: number; traffic: number; cpu: number; memory: number; disk: number }[]; simulationResult: ReturnType<typeof runCapacitySimulation> | null };
const C={navy:[22,41,67] as const,blue:[44,103,180] as const,teal:[32,132,125] as const,amber:[206,137,34] as const,red:[190,74,65] as const,green:[45,132,91] as const,text:[37,49,66] as const,muted:[95,109,128] as const,border:[214,222,232] as const,light:[247,249,252] as const,white:[255,255,255] as const};
const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
const txt=(e:Element|null|undefined)=>e?.textContent?.replace(/\s+/g,' ').trim()||'';
const num=(s:string)=>Number((s||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/)?.[0]||0);
const selectValue=(label:RegExp,fallback:string)=>[...document.querySelectorAll<HTMLSelectElement>('select')].find(s=>label.test(s.previousElementSibling?.textContent||''))?.value||fallback;
const nav=(name:string)=>[...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find(b=>b.innerText.trim()===name)?.click();
async function waitFor(test:()=>boolean,timeout=30000){const start=Date.now();while(Date.now()-start<timeout){if(test())return true;await sleep(250);}return false;}
function metricMeta(panel:Element):[string,string]{const t=txt(panel.querySelector('h2,.chart-title-row strong')).toLowerCase();if(t.includes('memory'))return['Memory utilization','%'];if(t.includes('disk'))return['Disk utilization','%'];if(t.includes('network rx'))return['Network RX','B/s'];if(t.includes('network tx'))return['Network TX','B/s'];if(t.includes('throughput'))return['Application throughput','req/min'];return['CPU utilization','%'];}
function captureCharts():Chart[]{return[...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg,.forecast-band-wrap svg')].map(svg=>{const panel=svg.closest('.chart-panel,.forecast-panel,.forecast-band-wrap')||svg.parentElement||svg;const[title,unit]=metricMeta(panel);return{title,unit,svg:svg.cloneNode(true) as SVGSVGElement,context:svg.closest('.forecast-panel')?'forecast':'history'};});}
function captureKpis():Kpi[]{return[...document.querySelectorAll<HTMLElement>('.metric-card')].map(card=>({label:txt(card.querySelector('p')),value:txt(card.querySelector('strong')),detail:txt(card.querySelector('small'))})).filter(k=>k.label&&k.value).slice(0,8);}
function captureTrafficSimulation(){const sliders=[...document.querySelectorAll<HTMLInputElement>('.simulation-controls input[type="range"]')];const growth=Number(sliders[0]?.value??0);const additionalHosts=Number(sliders[1]?.value??0);return{growth:Number.isFinite(growth)?growth:0,additionalHosts:Number.isFinite(additionalHosts)?additionalHosts:0};}
function parseTimeRange(value:string):TimeRange{if(value==='1h'||/1 hour/i.test(value))return'1h';if(value==='6h'||/6 hours/i.test(value))return'6h';if(value==='7d'||/7 days/i.test(value))return'7d';if(value==='30d'||/30 days/i.test(value))return'30d';return'24h';}
function parseHorizon(value:string):ForecastHorizon{const n=Number(value);return n===60||n===90?n:30;}
function avgCurrent(hosts:Host[],key:'cpu'|'memory'|'disk'){return hosts.length?hosts.reduce((sum,h)=>sum+(h.telemetry.at(-1)?.[key]??0),0)/hosts.length:0;}
function hostThroughput(hosts:Host[]){return hosts.reduce((sum,h)=>sum+(h.telemetry.at(-1)?.throughput??0),0);}
function captureHostTable():HostRow[]{return[...document.querySelectorAll<HTMLTableRowElement>('table tbody tr')].map(r=>{const c=[...r.cells].map(txt);return{host:c[0]||'—',environment:c[1]||'—',application:c[2]||'—',cpu:c[3]||'—',memory:c[4]||'—',disk:c[5]||'—',throughput:c[6]||'—',status:c[7]||c.at(-1)||'—'};}).filter(h=>h.host!=='—');}
async function collectLive(range:TimeRange,zone:string,horizon:ForecastHorizon,metric:MetricKey,growth:number,additionalHosts:number){const hosts=await dynatraceDataProvider.getHosts(zone,range);const currentTraffic=Math.max(1,hostThroughput(hosts));const cpu=Math.max(1,avgCurrent(hosts,'cpu')),memory=Math.max(1,avgCurrent(hosts,'memory')),disk=Math.max(1,avgCurrent(hosts,'disk'));const model=(day:number)=>day===0?{projectedCpu:cpu,projectedMemory:memory,projectedDisk:disk,risk:'Low' as const,capacityGap:0,recommendedExpansion:0,requiredHosts:0}:runCapacitySimulation({cpuCapacity:cpu,memoryCapacity:memory,diskCapacity:disk,trafficGrowth:growth,transactionGrowth:growth,period:day,additionalHosts,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});const resourceTrajectory=[0,30,60,90].map(day=>{const m=model(day);return{day,traffic:currentTraffic*(1+growth/100)**(day/90),cpu:m.projectedCpu,memory:m.projectedMemory,disk:m.projectedDisk};});let forecast:{host:Host;forecast:DynatraceForecast}|null=null;try{const results=await getDynatraceForecasts(hosts,metric,horizon);forecast=results.find(x=>x.forecast.forecast.length>0)||results[0]||null;}catch{forecast=null;}let aiText='',aiSource='Unavailable';try{const ai=await generateAssistCapacitySummary(hosts,zone,forecast?[forecast]:[]);aiText=ai.text;aiSource=ai.source;}catch(error){aiText=`Capacity assessment unavailable. ${error instanceof Error?error.message:String(error)}`;}return{hosts,currentTraffic,resourceTrajectory,forecast,aiText,aiSource};}
async function collect():Promise<ReportData>{nav('Simulation');await sleep(650);const scenario=captureTrafficSimulation();const zone=selectValue(/management zone/i,'All Management Zones');const rangeLabel=selectValue(/current data/i,'24h');const range=parseTimeRange(rangeLabel);const horizon=parseHorizon(selectValue(/^forecast$/i,'30'));const metricValue=selectValue(/metric/i,'cpu');const metric:MetricKey=metricValue==='memory'||metricValue==='disk'?metricValue:'cpu';const direct=await collectLive(range,zone,horizon,metric,scenario.growth,scenario.additionalHosts);const findings=[`${direct.hosts.length} host(s) are included in the selected scope. Average CPU ${avgCurrent(direct.hosts,'cpu').toFixed(1)}%, memory ${avgCurrent(direct.hosts,'memory').toFixed(1)}%, disk ${avgCurrent(direct.hosts,'disk').toFixed(1)}%.`,`The Simulation traffic slider is set to +${scenario.growth}% at report generation time; the report does not use a default growth value.`,`Traffic progresses from ${direct.currentTraffic.toFixed(1)} req/min now to ${direct.resourceTrajectory.at(-1)?.traffic.toFixed(1)} req/min at 90 days.`,direct.forecast?.forecast.forecast.length?`Dynatrace Intelligence returned a ${direct.forecast.forecast.horizon}-day ${direct.forecast.forecast.metric.toUpperCase()} forecast.`:'Dynatrace Intelligence forecast was unavailable at report generation time.'];nav('Host Inventory');await sleep(500);const hostRows=captureHostTable();const charts:Chart[]=[];const first=document.querySelector<HTMLTableRowElement>('table tbody tr');if(first){first.click();await sleep(550);for(const key of ['throughput','cpu','memory','disk','networkRx','networkTx']){const s=[...document.querySelectorAll<HTMLSelectElement>('select')].find(x=>['throughput','cpu','memory','disk','networkRx','networkTx'].includes(x.value));if(!s)continue;s.value=key;s.dispatchEvent(new Event('change',{bubbles:true}));await waitFor(()=>Boolean(document.querySelector('.chart-wrap svg')),7000);const c=captureCharts().filter(x=>x.context==='history').at(-1);if(c)charts.push(c);}}
nav('Capacity Forecast');await sleep(600);if(!document.querySelector('.forecast-panel svg')){const b=[...document.querySelectorAll<HTMLButtonElement>('button')].find(x=>/Run .*forecast/i.test(x.innerText));if(b)b.click();await waitFor(()=>Boolean(document.querySelector('.forecast-panel svg')),45000);}const fc=captureCharts().find(x=>x.context==='forecast');if(fc)charts.push(fc);const simulationResult=runCapacitySimulation({cpuCapacity:avgCurrent(direct.hosts,'cpu'),memoryCapacity:avgCurrent(direct.hosts,'memory'),diskCapacity:avgCurrent(direct.hosts,'disk'),trafficGrowth:scenario.growth,transactionGrowth:scenario.growth,period:90,additionalHosts:scenario.additionalHosts,cpuPerHost:25,memoryPerHost:25,diskPerHost:20});return{generated:new Date().toLocaleString('en-IN'),zone,range:rangeLabel,horizon,kpis:captureKpis().length?captureKpis():[{label:'Total Hosts',value:String(direct.hosts.length),detail:'Live from Dynatrace'},{label:'Traffic',value:`${direct.currentTraffic.toFixed(1)} req/min`,detail:'Live host telemetry'}],findings,aiText:direct.aiText,aiSource:direct.aiSource,charts,forecast:direct.forecast?.forecast??null,forecastHost:direct.forecast?.host.name??'Selected scope',hosts:hostRows.length?hostRows:direct.hosts.map(h=>{const p=h.telemetry.at(-1);return{host:h.name,environment:h.environment,application:h.application,cpu:`${Math.round(p?.cpu??0)}%`,memory:`${Math.round(p?.memory??0)}%`,disk:`${Math.round(p?.disk??0)}%`,throughput:`${Math.round(p?.throughput??0)} req/min`,status:h.profile};}),currentTraffic:direct.currentTraffic,trafficGrowth:scenario.growth,additionalHosts:scenario.additionalHosts,trafficTrajectory:direct.resourceTrajectory.map(x=>({day:x.day,value:x.traffic})),resourceTrajectory:direct.resourceTrajectory,simulationResult};}
function fill(doc:jsPDF,c:readonly number[]){doc.setFillColor(c[0],c[1],c[2]);}function stroke(doc:jsPDF,c:readonly number[]){doc.setDrawColor(c[0],c[1],c[2]);}function color(doc:jsPDF,c:readonly number[]){doc.setTextColor(c[0],c[1],c[2]);}
function header(doc:jsPDF,r:ReportData,title:string,sub:string){fill(doc,C.navy);doc.rect(0,0,595,82,'F');color(doc,C.white);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES',38,25);doc.setFontSize(19);doc.text(title,38,49);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(sub,38,66);doc.text(r.generated,557,25,{align:'right'});}
function footer(doc:jsPDF,p:number,total:number){stroke(doc,C.border);doc.line(38,790,557,790);color(doc,C.muted);doc.setFontSize(7);doc.text('Axis Davis Capacity Planner · Live Dynatrace telemetry · Management planning report',38,805);doc.text(`${p} / ${total}`,557,805,{align:'right'});}
function wrap(doc:jsPDF,value:string,x:number,y:number,w:number,size=8.5,lead=12){doc.setFontSize(size);const lines=doc.splitTextToSize(value,w);doc.text(lines,x,y);return y+lines.length*lead;}
function kpi(doc:jsPDF,x:number,y:number,w:number,k:Kpi,tone:readonly number[]=C.blue){fill(doc,C.white);stroke(doc,C.border);doc.roundedRect(x,y,w,67,7,7,'FD');fill(doc,tone);doc.rect(x,y,4,67,'F');color(doc,C.muted);doc.setFontSize(7);doc.text(k.label,x+12,y+16);color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(k.value,x+12,y+36);doc.setFont('helvetica','normal');color(doc,C.muted);doc.setFontSize(7);doc.text(doc.splitTextToSize(k.detail,w-20).slice(0,2),x+12,y+50);}
function table(doc:jsPDF,x:number,y:number,widths:number[],headers:string[],rows:string[][],rowH=19){const total=widths.reduce((a,b)=>a+b,0);let yy=y;fill(doc,C.navy);doc.rect(x,yy,total,rowH,'F');color(doc,C.white);doc.setFont('helvetica','bold');doc.setFontSize(7);let xx=x;headers.forEach((h,i)=>{doc.text(h,xx+4,yy+12);xx+=widths[i];});yy+=rowH;rows.forEach((row,ri)=>{fill(doc,ri%2?C.light:C.white);stroke(doc,C.border);doc.rect(x,yy,total,rowH,'FD');color(doc,C.text);doc.setFont('helvetica','normal');doc.setFontSize(6.7);xx=x;row.forEach((cell,i)=>{doc.text(doc.splitTextToSize(String(cell),Math.max(20,widths[i]-8)).slice(0,2),xx+4,yy+11);xx+=widths[i];});yy+=rowH;});return yy;}
async function svgPng(svg:SVGSVGElement,width=1100,height=340){const clone=svg.cloneNode(true) as SVGSVGElement;clone.setAttribute('width',String(width));clone.setAttribute('height',String(height));clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.chart-grid{stroke:#dfe6ef}.chart-line.actual{fill:none;stroke:#2c67b4;stroke-width:3}.chart-line.forecast{fill:none;stroke:#ce8922;stroke-width:3;stroke-dasharray:7 5}.chart-line.upper{fill:none;stroke:#ce8922;stroke-dasharray:4 4}.forecast-band{fill:#ce8922;fill-opacity:.14}.threshold-line{stroke:#be4a41;stroke-dasharray:5 4}.chart-axis-label,.chart-axis-title,.threshold-label{font-family:Arial;font-size:11px;fill:#40566f}';clone.insertBefore(style,clone.firstChild);return await new Promise<string>((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return reject(new Error('canvas unavailable'));ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(image,0,0,width,height);resolve(canvas.toDataURL('image/png'));};image.onerror=()=>reject(new Error('SVG conversion failed'));image.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(new XMLSerializer().serializeToString(clone))}`;});}
async function addChart(doc:jsPDF,c:Chart,x:number,y:number,w:number,h:number){color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text(c.title,x,y);color(doc,C.muted);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${c.unit}`,x+w,y,{align:'right'});try{doc.addImage(await svgPng(c.svg,1100,Math.max(260,Math.round(h*2.1))),'PNG',x,y+7,w,h-7,undefined,'FAST');}catch{color(doc,C.muted);doc.text('Chart unavailable at capture time.',x,y+24);}}
function lineChart(doc:jsPDF,x:number,y:number,w:number,h:number,points:Point[],title:string,unit:string){color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text(title,x,y);color(doc,C.muted);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${unit}`,x+w,y,{align:'right'});const left=x+40,right=x+w-12,top=y+20,bottom=y+h-20,max=Math.max(1,...points.map(p=>p.value)),min=Math.min(0,...points.map(p=>p.value));for(let i=0;i<=4;i++){const gy=top+(bottom-top)*i/4;stroke(doc,C.border);doc.line(left,gy,right,gy);color(doc,C.muted);doc.setFontSize(6.5);doc.text((max-(max-min)*i/4).toFixed(0),x,gy+2);}if(points.length<2)return;const coords=points.map((p,i)=>({x:left+(right-left)*i/(points.length-1),y:bottom-(p.value-min)/Math.max(1,max-min)*(bottom-top)}));stroke(doc,C.blue);doc.setLineWidth(2.2);for(let i=1;i<coords.length;i++)doc.line(coords[i-1].x,coords[i-1].y,coords[i].x,coords[i].y);doc.setLineWidth(0.2);coords.forEach((c,i)=>{fill(doc,C.white);stroke(doc,C.blue);doc.circle(c.x,c.y,3,'FD');color(doc,C.text);doc.setFontSize(6.5);doc.text(points[i].day===0?'Now':`${points[i].day}d`,c.x-7,bottom+12);doc.text(points[i].value.toFixed(1),c.x-10,c.y-8);});}
function aiSections(text:string){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const sections:{title:string;body:string}[]=[];let title='Capacity Assessment';let body:string[]=[];const flush=()=>{if(body.length)sections.push({title,body:body.join(' ')});body=[];};for(const raw of lines){const clean=raw.replace(/^#+\s*/,'').replace(/^[-•]\s*/,'');if(/^(Executive Summary|Key Findings|Capacity Risks|Recommended Actions|30\/60\/90-day planning recommendation|30\/60\/90-Day Planning Recommendation)$/i.test(clean)){flush();title=clean;}else body.push(clean);}flush();return sections.length?sections:[{title,body:text}];}
async function buildReport(r:ReportData){const doc=new jsPDF({unit:'pt',format:'a4'});const total=7;let p=1;header(doc,r,'Capacity & Performance Report','Executive management view · live Dynatrace data');let y=108;color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Executive Summary',38,y);y+=22;y=wrap(doc,`Management Zone: ${r.zone}. Current data: ${r.range}. Forecast horizon: ${r.horizon} days. Active simulation: +${r.trafficGrowth}% traffic growth with ${r.additionalHosts} additional host(s).`,38,y,515,8.7,12)+10;r.kpis.slice(0,6).forEach((k,i)=>kpi(doc,38+(i%3)*172,y+Math.floor(i/3)*77,158,k,i===4?C.green:i===5?C.amber:C.blue));y+=170;color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Key Findings',38,y);y+=16;r.findings.forEach(f=>{y=wrap(doc,`• ${f}`,46,y,505,8.5,12)+3;});footer(doc,p++,total);
  doc.addPage();header(doc,r,'AI Capacity Assessment',`Dynatrace Assist source: ${r.aiSource}`);y=108;if(!r.aiText)y=wrap(doc,'Dynatrace Assist did not return an assessment during report generation. No AI text has been fabricated.',42,y,500,9,13);else for(const s of aiSections(r.aiText)){color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(s.title,42,y);y+=16;y=wrap(doc,s.body,48,y,492,8.4,12)+12;}footer(doc,p++,total);
  doc.addPage();header(doc,r,'Infrastructure Trend Analysis','CPU, memory and disk utilization from live host telemetry.');y=108;for(const c of r.charts.filter(c=>c.context==='history'&&['CPU utilization','Memory utilization','Disk utilization'].includes(c.title)).slice(0,3)){await addChart(doc,c,42,y,510,145);y+=165;}footer(doc,p++,total);
  doc.addPage();header(doc,r,'Application & Network Performance','Application throughput and network telemetry from the selected host.');y=108;for(const c of r.charts.filter(c=>c.context==='history'&&!['CPU utilization','Memory utilization','Disk utilization'].includes(c.title)).slice(0,3)){await addChart(doc,c,42,y,510,145);y+=165;}footer(doc,p++,total);
  doc.addPage();header(doc,r,'Dynatrace Intelligence Forecast',`Metric: ${r.forecast?.metric?.toUpperCase()||'—'} · Horizon: ${r.horizon} days · ${r.forecastHost}`);y=108;const fc=r.charts.find(c=>c.context==='forecast');if(fc){await addChart(doc,fc,42,y,510,320);y+=342;}else{y=wrap(doc,'No rendered forecast chart was available at report generation time.',42,y,500,9,13)+20;}if(r.forecast){const f=r.forecast,peak=f.forecast.length?Math.max(...f.forecast):NaN,upper=f.upperBound.length?Math.max(...f.upperBound):NaN;color(doc,C.text);doc.setFontSize(8);doc.text(`Source: ${f.source} · Status: ${f.status} · Quality: ${f.quality}`,42,y);y+=16;doc.text(`Forecast end: ${f.forecastEnd?new Date(f.forecastEnd).toLocaleString('en-IN'):'—'} · Peak: ${Number.isFinite(peak)?peak.toFixed(1):'—'} · Upper bound peak: ${Number.isFinite(upper)?upper.toFixed(1):'—'}`,42,y);}footer(doc,p++,total);
  doc.addPage();header(doc,r,'Host Resource Utilization','Current host inventory for the selected scope.');y=108;table(doc,42,y,[170,65,92,45,50,45,65,55],['Host','Env','Application','CPU','Memory','Disk','Throughput','Status'],r.hosts.map(h=>[h.host,h.environment,h.application,h.cpu,h.memory,h.disk,h.throughput,h.status]),18);footer(doc,p++,total);
  doc.addPage();header(doc,r,'Traffic Simulation & Capacity Outlook',`Exact active scenario: +${r.trafficGrowth}% traffic growth · ${r.additionalHosts} additional host(s)`);y=108;lineChart(doc,42,y,510,190,r.trafficTrajectory,'Traffic Simulation Trajectory','req/min');y+=220;color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('30 / 60 / 90-Day Resource Outlook',42,y);y+=16;table(doc,42,y,[75,105,90,100,90],['Horizon','Traffic','CPU','Memory','Disk'],r.resourceTrajectory.map(x=>[x.day===0?'Now':`${x.day} days`,`${x.traffic.toFixed(1)} req/min`,`${x.cpu.toFixed(1)}%`,`${x.memory.toFixed(1)}%`,`${x.disk.toFixed(1)}%`]),19);y+=110;color(doc,C.navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('What-If Capacity Comparison',42,y);y+=16;const cur=r.resourceTrajectory[0],s90=r.resourceTrajectory.at(-1);if(cur&&s90)table(doc,42,y,[145,115,115,115],['Metric','Current','90-day scenario','Delta'],[['CPU',`${cur.cpu.toFixed(1)}%`,`${s90.cpu.toFixed(1)}%`,`${(s90.cpu-cur.cpu).toFixed(1)} pp`],['Memory',`${cur.memory.toFixed(1)}%`,`${s90.memory.toFixed(1)}%`,`${(s90.memory-cur.memory).toFixed(1)} pp`],['Disk',`${cur.disk.toFixed(1)}%`,`${s90.disk.toFixed(1)}%`,`${(s90.disk-cur.disk).toFixed(1)} pp`]],19);if(r.simulationResult)wrap(doc,`Scenario risk: ${r.simulationResult.risk} · Capacity gap: ${r.simulationResult.capacityGap} · Recommended expansion: ${r.simulationResult.recommendedExpansion} host(s).`,42,y+92,500,8.5,12);footer(doc,p++,total);
  doc.save('axis-capacity-report.pdf');}
export function installProductionPdfV5(){const w=window as Window&{__axisPdfV7?:boolean};if(w.__axisPdfV7)return;w.__axisPdfV7=true;document.addEventListener('click',async(e)=>{const button=e.target instanceof Element?e.target.closest('.pdf-report-button'):null;if(!button)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();(button as HTMLButtonElement).disabled=true;try{await buildReport(await collect());}catch(error){console.error('Axis PDF generation',error);alert(`PDF generation failed: ${error instanceof Error?error.message:String(error)}`);}finally{(button as HTMLButtonElement).disabled=false;}},true);}
