import { jsPDF } from 'jspdf';

type ChartSnap = { title: string; unit: string; svg: SVGSVGElement };
type Snap = { page: string; title: string; charts: ChartSnap[]; ai: string; scenario: string };
const sleep=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
async function waitFor(fn:()=>boolean,timeout=45000){const s=Date.now();while(Date.now()-s<timeout){if(fn())return true;await sleep(500);}return false;}
function activePage(){return document.querySelector('.nav-item.active')?.textContent?.trim()||'';}
function navigate(name:string){[...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find(x=>x.innerText.trim()===name)?.click();}
function clickText(re:RegExp){const b=[...document.querySelectorAll<HTMLButtonElement>('button')].find(x=>re.test(x.innerText.trim()));b?.click();return b;}
function charts():ChartSnap[]{return [...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg, .projection-svg')].map(svg=>{const row=svg.parentElement?.querySelector('.chart-title-row');return{title:row?.querySelector('strong')?.textContent?.trim()||svg.getAttribute('aria-label')||'Trend',unit:row?.querySelector('span')?.textContent?.match(/Unit:\s*([^·]+)/)?.[1]?.trim()||'',svg};});}
function aiText(){for(const sel of ['.ai-summary','.ai-assessment','.assist-summary','.ai-panel']){const e=document.querySelector<HTMLElement>(sel);if(e?.innerText?.trim())return e.innerText.trim();}return [...document.querySelectorAll<HTMLElement>('[class*="ai" i]')].map(x=>x.innerText?.trim()||'').filter(x=>x.length>120).sort((a,b)=>b.length-a.length)[0]||'';}
function scenarioText(){return document.querySelector<HTMLElement>('.simulation-scenario-detail')?.innerText?.trim()||'';}
async function svgPng(svg:SVGSVGElement,w=1000,h=380){const clone=svg.cloneNode(true) as SVGSVGElement;clone.setAttribute('width',String(w));clone.setAttribute('height',String(h));clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const ns='http://www.w3.org/2000/svg';const style=document.createElementNS(ns,'style');style.textContent=`.chart-grid{stroke:#e8eef5;stroke-width:1}.chart-line{fill:none;stroke-width:2.5}.actual{stroke:#377fe6}.forecast{stroke:#f09a3d;stroke-dasharray:7 5}.upper{stroke:#f5c785;stroke-width:1.5;stroke-dasharray:4 5}.threshold-line{stroke:#e4755b;stroke-dasharray:4 4;stroke-width:1.3}.forecast-split{stroke:#a6b5c8;stroke-width:1;stroke-dasharray:4 4}.projection-line{fill:none;stroke:#2f80ed;stroke-width:3}.projection-point{fill:#fff;stroke:#2f80ed;stroke-width:2}.scenario-line.actual{fill:none;stroke:#377fe6;stroke-width:2.5}.scenario-line.forecast{fill:none;stroke:#f09a3d;stroke-width:2.5}.chart-axis-label{font-family:Arial,sans-serif;font-size:10px;fill:#52677f}.chart-axis-title{font-family:Arial,sans-serif;font-size:10px;fill:#52677f}.threshold-label,.projection-label,.scenario-start-label,.scenario-end-label{font-family:Arial,sans-serif;font-size:10px;fill:#52677f}.chart-point{fill:#fff;stroke-width:2}`;clone.insertBefore(style,clone.firstChild);const xml=new XMLSerializer().serializeToString(clone);const src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(xml);return await new Promise<string>((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx){reject(new Error('Canvas unavailable'));return;}ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/png'));};img.onerror=()=>reject(new Error('Chart rasterization failed'));img.src=src;});}
function wrap(doc:jsPDF,text:string,x:number,y:number,width:number,size=8,leading=11){doc.setFontSize(size);const lines=doc.splitTextToSize(text,width);doc.text(lines,x,y);return y+lines.length*leading;}
async function addChart(doc:jsPDF,c:ChartSnap,x:number,y:number,w:number,h:number){doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(c.title,x,y);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`Unit: ${c.unit||'value'}`,x+w-85,y);try{doc.addImage(await svgPng(c.svg,1000,Math.round(h*2.5)),'PNG',x,y+7,w,h-12,undefined,'FAST');}catch{doc.setFontSize(8);doc.text('Chart could not be rendered.',x,y+25);}}
function header(doc:jsPDF,title:string,sub:string){doc.setTextColor(20,35,56);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES',40,32);doc.setFontSize(18);doc.text(title,40,53);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(sub,40,65);doc.text(`Generated ${new Date().toLocaleString('en-IN')}`,40,77);}
function snap():Snap{return{page:activePage(),title:document.querySelector('.page-title h1')?.textContent?.trim()||'Capacity Planner',charts:charts(),ai:aiText(),scenario:scenarioText()};}
async function collect(){const out:Snap[]=[];navigate('Overview');await sleep(600);if(!aiText()){const b=clickText(/Generate AI Assessment/i);if(b)await waitFor(()=>Boolean(aiText()),45000);}out.push(snap());navigate('Host Inventory');await sleep(800);const row=document.querySelector<HTMLTableRowElement>('tbody tr');if(row){row.click();await sleep(600);for(const metric of ['throughput','cpu','memory','disk','networkRx','networkTx']){const s=document.querySelector<HTMLSelectElement>('.chart-panel select');if(s){s.value=metric;s.dispatchEvent(new Event('change',{bubbles:true}));}await sleep(450);out.push(snap());}navigate('Host Inventory');await sleep(300);}navigate('Capacity Forecast');await sleep(800);const run=clickText(/Run .*forecast/i);if(run)await waitFor(()=>Boolean(document.querySelector('.chart-line.forecast')),45000);out.push(snap());navigate('Simulation');await sleep(900);await waitFor(()=>Boolean(document.querySelector('.simulation-scenario-detail')),45000);out.push(snap());return out;}
async function build(snaps:Snap[]){const doc=new jsPDF({unit:'pt',format:'a4'});const W=595;const overview=snaps.find(s=>/Overview/i.test(s.page))||snaps[0];header(doc,'Executive Capacity Report',overview?.title||'Capacity Planner');let y=105;doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Capacity at a glance',40,y);y+=18;doc.setFont('helvetica','normal');const cards=[...document.querySelectorAll<HTMLElement>('.metric-card')].slice(0,8).map(e=>e.innerText.replace(/\s+/g,' ').trim()).filter(Boolean);for(const c of cards){y=wrap(doc,c,40,y,W-80,8,11)+3;}const ai=overview?.ai||'Dynatrace Assist summary was not available during this report run. No recommendation text has been fabricated.';doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('AI-assisted capacity assessment',40,Math.max(y+12,330));doc.setFont('helvetica','normal');let ay=Math.max(y+30,348);for(const line of ai.split(/\n+/).filter(Boolean).slice(0,18)){if(ay>770)break;ay=wrap(doc,line,40,ay,W-80,8,11)+2;}
const hostCharts=snaps.filter(s=>/Host Inventory/i.test(s.page)).flatMap(s=>s.charts).filter((c,i,a)=>i===a.findIndex(x=>x.title===c.title));doc.addPage();header(doc,'Infrastructure Trend Analysis','CPU, memory, disk, throughput and network trends with explicit metric labels and date axes.');y=105;for(const c of hostCharts.slice(0,6)){if(y>650){doc.addPage();header(doc,'Infrastructure Trend Analysis','Continued infrastructure trends.');y=105;}await addChart(doc,c,48,y,500,105);y+=118;}
const forecast=snaps.find(s=>/Capacity Forecast/i.test(s.page));doc.addPage();header(doc,'Dynatrace Forecast','Observed telemetry and Dynatrace Intelligence forecast with correct visual chart rendering.');const fc=(forecast?.charts||[]).filter(c=>c.svg.querySelector('.chart-line.forecast'));if(fc.length){for(const c of fc.slice(0,2))await addChart(doc,c,48,105,500,300);}else{doc.setFontSize(10);doc.text('No usable Dynatrace forecast points were returned for this run. No forecast line has been fabricated.',48,130);}
const sim=snaps.find(s=>/Simulation/i.test(s.page));doc.addPage();header(doc,'Traffic What-if & Resource Capacity','Scenario traffic change and resulting CPU, memory and disk outlook at 20 / 60 / 90 days.');y=105;if(sim?.scenario)y=wrap(doc,sim.scenario,48,y,500,8,11)+15;const sc=(sim?.charts||[]).filter(c=>c.svg.classList.contains('projection-svg'));for(const c of sc.slice(0,3)){if(y>620){doc.addPage();header(doc,'Traffic What-if & Resource Capacity','Continued resource projections.');y=105;}await addChart(doc,c,48,y,500,175);y+=190;}
doc.addPage();header(doc,'AI Recommendations','Recommendations captured from the application run.');y=105;for(const line of ai.split(/\n+/).filter(Boolean)){if(y>780)break;y=wrap(doc,line,48,y,500,9,13)+3;}doc.save('axis-capacity-report.pdf');}
export function installProductionPdfV2(){const state=window as Window & {__axisProductionPdfV2?:boolean};if(state.__axisProductionPdfV2)return;state.__axisProductionPdfV2=true;document.addEventListener('click',async(e)=>{const b=e.target instanceof Element?e.target.closest('.pdf-report-button'):null;if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{await build(await collect());}catch(err){console.error('Production PDF generation failed',err);alert(`PDF generation failed: ${err instanceof Error?err.message:String(err)}`);}},true);}
