import { jsPDF } from 'jspdf';

type ChartSnap = { title: string; unit: string; svg: SVGSVGElement; context: string };
type HostRow = { name: string; environment: string; application: string; cpu: string; memory: string; disk: string; status: string };
type Snap = { page: string; charts: ChartSnap[]; ai: string; scenario: string; cards: string[]; hosts: HostRow[]; forecastMeta: string[] };

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
async function waitFor(test: () => boolean, timeout = 20000) { const s = Date.now(); while (Date.now() - s < timeout) { if (test()) return true; await sleep(250); } return false; }
function nav(name: string) { [...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find((b) => b.innerText.trim() === name)?.click(); }
function page() { return document.querySelector('.nav-item.active')?.textContent?.trim() || ''; }
function txt(e: Element | null) { return e?.textContent?.replace(/\s+/g, ' ').trim() || ''; }
const META: Record<string, [string, string]> = { cpu: ['CPU utilization', '%'], memory: ['Memory utilization', '%'], disk: ['Disk utilization', '%'], networkRx: ['Network RX', 'B/s'], networkTx: ['Network TX', 'B/s'], throughput: ['Application throughput', 'req/min'] };
function metric(panel: Element) { const s = panel.querySelector<HTMLSelectElement>('select'); if (s?.value && META[s.value]) return META[s.value]; const t = txt(panel.querySelector('.chart-title-row strong')).toLowerCase(); if (t.includes('memory')) return META.memory; if (t.includes('disk')) return META.disk; if (t.includes('network rx') || t.includes('receive')) return META.networkRx; if (t.includes('network tx') || t.includes('transmit')) return META.networkTx; if (t.includes('throughput')) return META.throughput; return META.cpu; }
function charts(): ChartSnap[] { return [...document.querySelectorAll<SVGSVGElement>('.chart-wrap svg,.forecast-band-wrap svg,.projection-svg')].map((svg) => { const panel = svg.closest('.chart-panel,.projection-card,.forecast-band-wrap') || svg.parentElement || svg; const [name, unit] = metric(panel); const context = panel.classList.contains('forecast-band-wrap') ? 'forecast' : panel.classList.contains('projection-card') || svg.classList.contains('projection-svg') ? 'simulation' : 'chart'; return { title: name, unit, context, svg: svg.cloneNode(true) as SVGSVGElement }; }); }
function cards(): string[] { return [...document.querySelectorAll<HTMLElement>('.metric-card')].map(txt).filter(Boolean).slice(0, 8); }
function hostRows(): HostRow[] { return [...document.querySelectorAll<HTMLTableRowElement>('tbody tr')].map((tr) => { const c = [...tr.cells].map((x) => txt(x)); return { name: c[0] || '—', environment: c[1] || '—', application: c[2] || '—', cpu: c[3] || '—', memory: c[4] || '—', disk: c[5] || '—', status: c[7] || c.at(-1) || '—' }; }).filter((r) => r.name !== '—'); }
function forecastMeta(): string[] { return [...document.querySelectorAll<HTMLElement>('.forecast-card,.forecast-result-card,.forecast-meta,.forecast-band-meta,.forecast-summary')].map(txt).filter(Boolean).slice(0, 8); }
function snap(): Snap { return { page: page(), charts: charts(), ai: document.querySelector<HTMLElement>('.ai-assessment')?.innerText?.trim() || '', scenario: document.querySelector<HTMLElement>('.simulation-scenario-detail')?.innerText?.trim() || '', cards: cards(), hosts: hostRows(), forecastMeta: forecastMeta() }; }
async function setMetric(key: string) { const s = [...document.querySelectorAll<HTMLSelectElement>('select')].find((x) => META[x.value] || /metric/i.test(x.previousElementSibling?.textContent || '')); if (!s) return; s.value = key; s.dispatchEvent(new Event('change', { bubbles: true })); await sleep(500); await waitFor(() => Boolean(document.querySelector('.chart-wrap svg')), 5000); }
async function collect() {
  const out: Snap[] = [];
  nav('Overview'); await sleep(500); out.push(snap());
  nav('Host Inventory'); await sleep(800); const inv = snap(); if (inv.hosts.length) { const row = document.querySelector<HTMLTableRowElement>('tbody tr'); if (row) row.click(); await sleep(500); for (const k of ['throughput', 'cpu', 'memory', 'disk', 'networkRx', 'networkTx']) { await setMetric(k); const s = snap(); s.hosts = inv.hosts; out.push(s); } } else out.push(inv);
  nav('Capacity Forecast'); await sleep(700); if (!document.querySelector('.chart-panel svg')) { const b = [...document.querySelectorAll<HTMLButtonElement>('button')].find((x) => /Run .*forecast/i.test(x.innerText)); if (b) b.click(); await waitFor(() => Boolean(document.querySelector('.chart-panel svg')), 20000); } out.push(snap());
  nav('Simulation'); await sleep(700); await waitFor(() => document.querySelectorAll('.projection-svg').length >= 3, 20000); out.push(snap());
  return out;
}
function svgPng(svg: SVGSVGElement, w = 1100, h = 420) { const csvg = svg.cloneNode(true) as SVGSVGElement; csvg.setAttribute('width', String(w)); csvg.setAttribute('height', String(h)); csvg.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); const style = document.createElementNS('http://www.w3.org/2000/svg', 'style'); style.textContent = '.chart-grid{stroke:#dfe6ef;stroke-width:1}.chart-line.actual{fill:none;stroke:#327fe6;stroke-width:3}.chart-line.forecast{fill:none;stroke:#e88b32;stroke-width:3;stroke-dasharray:7 5}.chart-line.upper{fill:none;stroke:#e88b32;stroke-width:1.5;stroke-dasharray:4 4}.forecast-band{fill:#e88b32;fill-opacity:.16}.threshold-line{stroke:#d55d4b;stroke-width:1.5;stroke-dasharray:5 4}.chart-axis-label,.chart-axis-title,.threshold-label,.projection-label{font-family:Arial,sans-serif;font-size:11px;fill:#40566f}.projection-line{fill:none;stroke:#327fe6;stroke-width:3}.projection-point{fill:#fff;stroke:#327fe6;stroke-width:2}.forecast-split{stroke:#9aaabd;stroke-width:1;stroke-dasharray:4 4}'; csvg.insertBefore(style, csvg.firstChild); return new Promise<string>((resolve, reject) => { const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); c.width = w; c.height = h; const ctx = c.getContext('2d'); if (!ctx) return reject(new Error('canvas')); ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, w, h); ctx.drawImage(img, 0, 0, w, h); resolve(c.toDataURL('image/png')); }; img.onerror = () => reject(new Error('svg')); img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(new XMLSerializer().serializeToString(csvg)); }); }
function wrap(doc: jsPDF, s: string, x: number, y: number, w: number, size = 8.5, lead = 12) { doc.setFontSize(size); const lines = doc.splitTextToSize(s, w); doc.text(lines, x, y); return y + lines.length * lead; }
function header(doc: jsPDF, title: string, sub: string) { doc.setTextColor(20, 35, 56); doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text('AXIS BANK  |  ApMoSys TECHNOLOGIES', 40, 30); doc.setFontSize(18); doc.text(title, 40, 53); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.text(sub, 40, 66); doc.text(`Generated ${new Date().toLocaleString('en-IN')}`, 40, 78); doc.setDrawColor(215, 222, 232); doc.line(40, 86, 555, 86); }
function footer(doc: jsPDF, pageNo: number) { doc.setFontSize(7); doc.setTextColor(110, 120, 135); doc.text('Axis Davis Capacity Planner · Live Dynatrace telemetry · Planning report', 40, 815); doc.text(`Page ${pageNo}`, 520, 815); }
async function addChart(doc: jsPDF, c: ChartSnap, x: number, y: number, w: number, h: number) { doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(20, 35, 56); doc.text(c.title, x, y); doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.text(`Unit: ${c.unit}`, x + w - 70, y); try { doc.addImage(await svgPng(c.svg, 1100, Math.max(280, Math.round(h * 2.2))), 'PNG', x, y + 8, w, h - 10, undefined, 'FAST'); } catch { doc.setFontSize(8); doc.text('Chart could not be rendered from the captured application state.', x, y + 28); } }
function table(doc: jsPDF, headers: string[], rows: string[][], x: number, y: number, widths: number[], rowH = 17) { const drawRow = (cells: string[], head: boolean) => { let xx = x; doc.setFillColor(head ? 38 : 248, head ? 82 : 250, head ? 124 : 252); doc.setDrawColor(215, 222, 232); doc.setFont('helvetica', head ? 'bold' : 'normal'); doc.setFontSize(head ? 7 : 6.8); cells.forEach((cell, i) => { doc.rect(xx, y, widths[i], rowH, 'FD'); doc.setTextColor(head ? 255 : 35, head ? 255 : 45, head ? 255 : 60); doc.text(doc.splitTextToSize(cell, widths[i] - 6).slice(0, 2), xx + 3, y + 11); xx += widths[i]; }); y += rowH; }; drawRow(headers, true); for (const r of rows) { if (y > 780) break; drawRow(r, false); } return y; }
function num(s: string) { const m = s.replace(/,/g, '').match(/-?\d+(?:\.\d+)?/); return m ? Number(m[0]) : NaN; }
function buildRecommendations(sim: Snap | undefined, fc: Snap | undefined, hosts: HostRow[]) { const lines: string[] = []; const risk = hosts.filter((h) => /risk/i.test(h.status)).length; const watch = hosts.filter((h) => /watch/i.test(h.status)).length; if (risk) lines.push(`${risk} host(s) are currently flagged At Risk by the application's live capacity status. Prioritize those hosts for capacity review.`); if (watch) lines.push(`${watch} host(s) are in Watch status. Review trend direction and recent workload before increasing capacity.`); if (fc?.forecastMeta.length) lines.push('Dynatrace Intelligence forecast results are included only when returned by the analyzer; no forecast values are fabricated.'); if (sim?.scenario) lines.push('Use the What-If scenario as a planning sensitivity analysis alongside live telemetry.'); if (!lines.length) lines.push('No deterministic risk finding was available from the captured application state. Continue monitoring live telemetry and rerun the forecast after meaningful workload changes.'); return lines; }
async function build(s: Snap[]) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' }); const overview = s.find((x) => /Overview/i.test(x.page)) || s[0]; const inv = s.find((x) => /Host Inventory/i.test(x.page)); const fc = s.find((x) => /Capacity Forecast/i.test(x.page)); const sim = s.find((x) => /Simulation/i.test(x.page)); const hosts = inv?.hosts || overview?.hosts || []; let pageNo = 1;
  header(doc, 'Capacity & Performance Report', `${overview?.cards[0] || 'Live Dynatrace capacity planning snapshot'} · Selected forecast horizon`); let y = 112; doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.text('Executive summary', 40, y); y += 24;
  y = wrap(doc, 'This report summarizes the current Dynatrace telemetry available to Axis Davis Capacity Planner, the selected host inventory, Dynatrace Intelligence forecast results, and the traffic what-if simulation. Values are taken from the rendered application state at report generation time.', 40, y, 515, 9, 13) + 12;
  const kpis = overview?.cards || []; table(doc, ['Live capacity snapshot', 'Value'], kpis.map((v) => [v.slice(0, 38), v.slice(0, 78)]), 40, y, [175, 340], 22); y += Math.min(300, (kpis.length + 1) * 22 + 16);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text('Key findings', 40, y); y += 18; for (const line of buildRecommendations(sim, fc, hosts)) y = wrap(doc, `• ${line}`, 48, y, 500, 8.5, 12) + 4; footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Infrastructure Trend Analysis', 'Live host telemetry captured from the selected inventory state.'); y = 108; const infra = s.filter((x) => /Host Inventory/i.test(x.page));
  for (const key of ['cpu', 'memory', 'disk']) { const c = infra.find((x) => x.charts.some((z) => z.title.toLowerCase().includes(key)))?.charts.find((z) => z.title.toLowerCase().includes(key)); if (c) { await addChart(doc, c, 48, y, 500, 125); y += 145; } } footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Application & Network Telemetry', 'Observed throughput and network activity from the selected host.'); y = 108;
  for (const key of ['throughput', 'network rx', 'network tx']) { const c = infra.find((x) => x.charts.some((z) => z.title.toLowerCase().includes(key)))?.charts.find((z) => z.title.toLowerCase().includes(key)); if (c) { await addChart(doc, c, 48, y, 500, 145); y += 165; } }
  if (y < 400) { doc.setFont('helvetica', 'italic'); doc.setFontSize(8); doc.text('Application response-time and problem-count telemetry are not currently exposed by this report path, so they are intentionally not fabricated.', 48, y + 20); } footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Dynatrace Intelligence Forecast', 'Forecast values and prediction interval captured from the rendered Dynatrace analyzer result.'); y = 110; const forecastChart = fc?.charts.find((c) => c.context === 'chart' || c.context === 'forecast');
  if (forecastChart) { await addChart(doc, forecastChart, 48, y, 500, 310); y += 335; } else y = wrap(doc, 'No forecast chart was rendered by Dynatrace during capture. The report does not fabricate a forecast graph.', 48, y, 500, 9, 13) + 20;
  if (fc?.forecastMeta.length) { doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text('Forecast context', 48, y); y += 16; for (const m of fc.forecastMeta) y = wrap(doc, m, 48, y, 500, 8, 11) + 2; } footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Host Resource Utilization', 'Current host-level values and capacity status from live Dynatrace telemetry.'); y = 108; const sorted = [...hosts].sort((a, b) => { const rank = (s: string) => /risk/i.test(s) ? 0 : /watch/i.test(s) ? 1 : 2; return rank(a.status) - rank(b.status) || (num(b.memory) || 0) - (num(a.memory) || 0); });
  y = table(doc, ['Host', 'Environment', 'CPU', 'Memory', 'Disk', 'Status'], sorted.slice(0, 42).map((h) => [h.name, h.environment, h.cpu, h.memory, h.disk, h.status]), 32, y, [225, 72, 50, 58, 50, 60], 18); y += 12; doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.text(`Showing ${Math.min(42, sorted.length)} of ${sorted.length} hosts. Status values are the application's live classifications; no synthetic host forecasts are inserted.`, 32, y); footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Traffic What-If & Resource Capacity', 'Traffic scenario with separate CPU, memory and disk projections.'); y = 108; if (sim?.scenario) y = wrap(doc, sim.scenario, 48, y, 500, 8.5, 12) + 16; const pcs = sim?.charts.filter((c) => c.svg.classList.contains('projection-svg')) || [];
  for (const c of pcs) { if (y > 680) { doc.addPage(); header(doc, 'Traffic What-If & Resource Capacity', 'Continued resource projections.'); y = 105; } await addChart(doc, c, 48, y, 500, 155); y += 175; } if (!pcs.length) doc.text('No CPU, memory or disk scenario chart was rendered.', 48, y); footer(doc, pageNo++);

  doc.addPage(); header(doc, 'Capacity Planning Recommendations', 'Actionable findings based only on data available in the application state.'); y = 110; for (const r of buildRecommendations(sim, fc, hosts)) y = wrap(doc, `• ${r}`, 48, y, 500, 9, 14) + 6;
  y += 12; doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text('Report methodology & data provenance', 48, y); y += 18; const notes = ['Live telemetry: retrieved through the Dynatrace AppEngine query path used by Axis Davis Capacity Planner.', 'Forecast: values are shown only when Dynatrace Intelligence returns a rendered forecast result.', 'What-If simulation: uses the application selected traffic scenario and resource projections.', 'Host table: current CPU, memory, disk and status are copied from the live Host Inventory state.', 'Unavailable data is explicitly called out instead of being replaced with guessed values.']; for (const n of notes) y = wrap(doc, `• ${n}`, 48, y, 500, 8.5, 12) + 3;
  if (overview?.ai) { y += 12; doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text('AI-assisted assessment', 48, y); y += 16; for (const l of overview.ai.split(/\n+/).filter(Boolean).slice(0, 18)) y = wrap(doc, l, 48, y, 500, 8, 11) + 2; } footer(doc, pageNo++);
  doc.save('axis-capacity-report.pdf');
}
export function installProductionPdfV4() { const w = window as Window & { __axisPdfV5?: boolean }; if (w.__axisPdfV5) return; w.__axisPdfV5 = true; document.addEventListener('click', async (e) => { const b = e.target instanceof Element ? e.target.closest('.pdf-report-button') : null; if (!b) return; e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); b.setAttribute('disabled', 'true'); try { await build(await collect()); } catch (err) { console.error('PDF V5', err); alert(`PDF generation failed: ${err instanceof Error ? err.message : String(err)}`); } finally { b.removeAttribute('disabled'); } }, true); }
