type ChartInfo = { title: string; svg: SVGSVGElement; unit: string };
type PageState = { page: string; title: string; eyebrow: string; cards: string[]; charts: ChartInfo[]; ai: string; verification: string };

const esc = (value: string) => value.replace(/[\\()]/g, ' ').replace(/[^\x20-\x7E]/g, ' ');
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
async function waitFor(condition: () => boolean, timeoutMs: number, pollMs = 500) { const end = Date.now() + timeoutMs; while (Date.now() < end) { if (condition()) return true; await sleep(pollMs); } return condition(); }

function pdfText(page: string[], x: number, y: number, value: string, size = 10, bold = false) { page.push(`0 0 0 rg BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${esc(value)}) Tj ET`); }
function pdfLine(page: string[], x1: number, y1: number, x2: number, y2: number, color = '0.72 0.77 0.84 RG', width = 1) { page.push(`${color} ${width} w ${x1} ${y1} m ${x2} ${y2} l S`); }
function polylineToPdf(svg: SVGSVGElement, page: string[], points: string, box: { x: number; y: number; w: number; h: number }, color: string, fill = false) { const viewBox = svg.viewBox.baseVal; const source = points.trim().split(/\s+/).map((pair) => pair.split(',').map(Number)).filter(([x, y]) => Number.isFinite(x) && Number.isFinite(y)); if (source.length < 2) return; const mapped = source.map(([sx, sy]) => [box.x + (sx / Math.max(1, viewBox.width)) * box.w, box.y + box.h - (sy / Math.max(1, viewBox.height)) * box.h] as const); const path = mapped.map(([x, y], index) => `${x.toFixed(2)} ${y.toFixed(2)} ${index ? 'l' : 'm'}`).join(' '); if (fill) page.push(`${color} rg ${path} h f`); else page.push(`${color} RG 1.7 w ${path} S`); }
function chartToPdf(chart: ChartInfo, page: string[], x: number, y: number, w: number, h: number) { const title = chart.title || 'Trend'; pdfText(page, x, y + h + 24, title, 12, true); pdfText(page, x + w - 120, y + h + 24, `Unit: ${chart.unit || 'value'}`, 8); const box = { x, y, w, h }; pdfLine(page, x, y, x + w, y, '0.65 0.70 0.78 RG', 1); pdfLine(page, x, y, x, y + h, '0.65 0.70 0.78 RG', 1); const axisTexts = [...chart.svg.querySelectorAll<SVGTextElement>('.chart-axis-label')].map((node) => node.textContent?.trim() || '').filter(Boolean); const numericTicks = axisTexts.filter((value) => /^-?\d/.test(value)).slice(0, 5); const ticks = numericTicks.length === 5 ? numericTicks : ['100','75','50','25','0']; ticks.forEach((label, index) => { const yy = y + h * (ticks.length === 1 ? 0 : index / (ticks.length - 1)); pdfLine(page, x, yy, x + w, yy, '0.88 0.90 0.94 RG', .6); pdfText(page, x - 42, yy - 3, label, 7); }); const lines = [...chart.svg.querySelectorAll('polyline')]; for (const element of lines) { const classes = element.getAttribute('class') ?? ''; const points = element.getAttribute('points') ?? ''; if (classes.includes('actual') || classes.includes('scenario-line.actual')) polylineToPdf(chart.svg, page, points, box, '0.12 0.43 0.95'); else if (classes.includes('forecast') || classes.includes('scenario-line.forecast')) polylineToPdf(chart.svg, page, points, box, '0.92 0.43 0.12'); else if (classes.includes('upper')) polylineToPdf(chart.svg, page, points, box, '0.82 0.58 0.14'); } const band = chart.svg.querySelector('.forecast-band'); if (band) polylineToPdf(chart.svg, page, band.getAttribute('points') ?? '', box, '0.94 0.76 0.28', true); const split = chart.svg.querySelector('.forecast-split'); if (split) { const x1 = Number(split.getAttribute('x1') ?? 0); const sx = box.x + x1 / Math.max(1, chart.svg.viewBox.baseVal.width) * box.w; pdfLine(page, sx, y, sx, y + h, '0.50 0.58 0.68 RG', .8); pdfText(page, sx - 25, y - 16, 'Forecast starts', 7); } pdfText(page, x, y - 16, 'Window start', 8); pdfText(page, x + w / 2 - 20, y - 16, 'Midpoint', 8); pdfText(page, x + w - 32, y - 16, 'Latest', 8); pdfText(page, x + w / 2 - 16, y - 30, 'Time', 8); if (chart.svg.querySelector('.chart-line.forecast,.scenario-line.forecast')) pdfText(page, x + 8, y + h - 10, 'Blue: historical/current   Orange: forecast/simulated', 8); if (chart.svg.querySelector('.forecast-band')) pdfText(page, x + 8, y + h - 24, 'Gold: 90% prediction interval', 8); }
function collectTextCards() { return [...document.querySelectorAll<HTMLElement>('.metric-card')].slice(0, 12).map((element) => element.innerText.replace(/\n+/g, ' · ').trim()).filter(Boolean); }
function collectCharts(): ChartInfo[] { return [...document.querySelectorAll('.chart-wrap svg')].map((svg) => { const title = svg.parentElement?.querySelector('.chart-title-row strong')?.textContent?.trim() || svg.parentElement?.parentElement?.querySelector('h2')?.textContent?.trim() || 'Trend'; const unit = svg.parentElement?.querySelector('.chart-title-row span')?.textContent?.replace(/^Unit:\s*/i, '').split('·')[0].trim() || 'value'; return { title, svg: svg as SVGSVGElement, unit }; }); }
function collectPageState(): PageState { return { page: [...document.querySelectorAll('.nav-item')].find((button) => button.classList.contains('active'))?.textContent?.trim() || 'Overview', title: document.querySelector('.page-title h1')?.textContent?.trim() || 'Capacity Planner', eyebrow: document.querySelector('.page-title .eyebrow')?.textContent?.trim() || '', cards: collectTextCards(), charts: collectCharts(), ai: document.querySelector('.ai-summary')?.textContent?.trim() || '', verification: document.querySelector('.traffic-summary')?.textContent?.trim() || document.querySelector('.status-panel')?.textContent?.trim() || '' }; }
function clickNav(name: string) { const button = [...document.querySelectorAll<HTMLButtonElement>('.nav-item')].find((item) => item.innerText.trim() === name); button?.click(); return Boolean(button); }
function clickButtonMatching(text: RegExp) { const button = [...document.querySelectorAll<HTMLButtonElement>('button')].find((item) => text.test(item.innerText.trim())); button?.click(); return button; }
function setMetric(metric: string) { const select = document.querySelector<HTMLSelectElement>('.chart-panel select'); if (!select) return false; select.value = metric; select.dispatchEvent(new Event('change', { bubbles: true })); return true; }

function buildReport(pagesData: PageState[]) { const pages: string[][] = []; const makePage = (title: string, subtitle: string) => { const page: string[] = []; pdfText(page, 40, 750, 'AXIS BANK  |  ApMoSys TECHNOLOGIES', 11, true); pdfText(page, 40, 726, title, 17, true); pdfText(page, 40, 710, subtitle, 9); pdfText(page, 40, 692, 'Developer: Shaktiswarup Pahantasingh', 8); return page; }; const executive = pagesData.find((data) => data.page.includes('Overview')) ?? pagesData[0]; const forecastPage = pagesData.find((data) => data.page.includes('Capacity Forecast')); const simulationPage = pagesData.find((data) => data.page.includes('Simulation')); const hostPages = pagesData.filter((data) => data.title && data.charts.length > 0 && data.page.includes('Host Inventory')); const ai = pagesData.map((data) => data.ai).find((text) => text.trim()) || 'Dynatrace Assist did not return a usable AI analysis for this report run.';
  let page = makePage('Executive Capacity Report', `${executive?.title ?? 'Capacity Planner'} · generated ${new Date().toLocaleString()}`); let y = 660; (executive?.cards ?? []).slice(0, 7).forEach((card) => { pdfText(page, 40, y, card, 9); y -= 18; }); if (executive?.verification) { y -= 8; pdfText(page, 40, y, 'Application-service throughput verification', 11, true); y -= 18; executive.verification.split(/\n|\s{2,}/).filter(Boolean).slice(0, 8).forEach((line) => { pdfText(page, 40, y, line.slice(0, 110), 8); y -= 14; }); } pdfText(page, 40, Math.max(330, y - 6), 'AI-assisted capacity assessment', 11, true); ai.split(/\n+/).filter(Boolean).slice(0, 10).forEach((line, index) => pdfText(page, 40, Math.max(310, y - 25 - index * 14), line.slice(0, 105), 8)); pages.push(page);
  if (hostPages.length) { page = makePage('Infrastructure Trend Analysis', 'Actual host telemetry from the selected current-data window.'); hostPages.slice(0, 4).forEach((data, index) => { if (data.charts[0]) chartToPdf(data.charts[0], page, 55, 425 - index * 145, 500, 120); }); pages.push(page); } else { page = makePage('Infrastructure Trend Analysis', 'Data availability'); pdfText(page, 55, 620, 'No host-level trend chart was captured during report generation.', 10); pages.push(page); }
  page = makePage('Forecast and Simulation', forecastPage ? `${forecastPage.title} · Dynatrace Intelligence` : 'Forecast and simulation'); const forecastChart = forecastPage?.charts.find((chart) => chart.svg.querySelector('.chart-line.forecast')); if (forecastChart) { chartToPdf(forecastChart, page, 55, 410, 500, 220); pdfText(page, 55, 385, 'Interpretation', 10, true); pdfText(page, 55, 368, 'Orange = Dynatrace forecast · Gold = 90% prediction interval · Red = capacity threshold.', 8); } else pdfText(page, 55, 610, 'No usable Dynatrace forecast line was returned. The report does not fabricate a forecast.', 10); const simulationChart = simulationPage?.charts.find((chart) => chart.svg.querySelector('.scenario-line')); if (simulationChart) { chartToPdf(simulationChart, page, 55, 125, 500, 185); pdfText(page, 55, 105, 'Scenario assumption: linear ramp from current traffic to the simulated endpoint.', 8); } else pdfText(page, 55, 350, 'No simulation trend was captured.', 9); pages.push(page);
  page = makePage('AI Recommendations', 'Dynatrace Assist output grounded in the selected live scope and available forecast context.'); let ay = 650; ai.split(/\n+/).filter(Boolean).slice(0, 36).forEach((line) => { if (ay < 70) return; pdfText(page, 50, ay, line.slice(0, 110), 8); ay -= 16; }); pages.push(page);
  const kids = pages.map((_, i) => `${3 + i * 2} 0 R`).join(' '); const objects: string[] = ['<< /Type /Catalog /Pages 2 0 R >>', `<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>`]; pages.forEach((content, index) => { const pageNo = 3 + index * 2; const contentNo = pageNo + 1; const stream = content.join('\n'); objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 9 0 R /F2 10 0 R >> >> /Contents ${contentNo} 0 R >>`); objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`); }); objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'); let output = '%PDF-1.4\n'; const offsets: number[] = [0]; objects.forEach((object, index) => { offsets.push(output.length); output += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = output.length; output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([output], { type: 'application/pdf' })); anchor.download = 'axis-capacity-planner-executive-report.pdf'; anchor.click(); setTimeout(() => URL.revokeObjectURL(anchor.href), 1000); }

export function installPdfReportOverride() { document.addEventListener('click', async (event) => { const target = event.target instanceof Element ? event.target.closest('.pdf-report-button') : null; if (!target) return; event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); const active = document.querySelector('.nav-item.active'); const snapshots: PageState[] = [];
    clickNav('Capacity Forecast');
    await sleep(700);
    if (!document.querySelector('.chart-line.forecast')) { const run = clickButtonMatching(/Run .*forecast/i); if (run) { await waitFor(() => Boolean(document.querySelector('.chart-line.forecast')) || Boolean(document.querySelector('.chart-no-data')), 60000, 700); } }
    snapshots.push(collectPageState());
    clickNav('Overview');
    await sleep(700);
    if (!document.querySelector('.ai-summary')) { const aiButton = clickButtonMatching(/Generate AI Assessment/i); if (aiButton) await waitFor(() => Boolean(document.querySelector('.ai-summary')) || !/Analyzing/i.test(aiButton.innerText), 30000, 800); }
    snapshots.push(collectPageState());
    clickNav('Host Inventory');
    await sleep(700);
    const firstRow = document.querySelector<HTMLTableRowElement>('table tbody tr');
    if (firstRow) { firstRow.click(); await sleep(700); for (const metric of ['throughput','cpu','memory','disk']) { setMetric(metric); await sleep(350); snapshots.push(collectPageState()); } clickButtonMatching(/Back to inventory/i); await sleep(400); }
    clickNav('Simulation');
    await waitFor(() => Boolean(document.querySelector('.simulation-scenario-chart')), 5000, 500);
    snapshots.push(collectPageState());
    if (active instanceof HTMLButtonElement) active.click();
    await sleep(150);
    buildReport(snapshots);
  }, true); }
